"""domain schema: people events sponsors finance

Revision ID: 25c4ce13270d
Revises: 7b59509e3c76
Create Date: 2026-06-14 10:17:46.943216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '25c4ce13270d'
down_revision: Union[str, Sequence[str], None] = '7b59509e3c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('committee', sa.String(length=128), nullable=True),
    sa.Column('role_title', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_committee'), ['committee'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_type'), ['type'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('trimester', sa.String(length=32), nullable=True),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('venue', sa.String(length=256), nullable=True),
    sa.Column('event_lead_id', sa.Integer(), nullable=True),
    sa.Column('committee', sa.String(length=128), nullable=True),
    sa.Column('dusa_submission_status', sa.String(length=64), nullable=True),
    sa.Column('dusa_deadline', sa.Date(), nullable=True),
    sa.Column('dusa_required', sa.Boolean(), nullable=False),
    sa.Column('food_provided', sa.Boolean(), nullable=False),
    sa.Column('external_guests', sa.Boolean(), nullable=False),
    sa.Column('expected_attendance', sa.Integer(), nullable=True),
    sa.Column('actual_attendance', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_lead_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_dusa_deadline'), ['dusa_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_dusa_submission_status'), ['dusa_submission_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_lead_id'), ['event_lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)

    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation', sa.String(length=256), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('contact_person_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=64), nullable=True),
    sa.Column('value_aud', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dusa_approved', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contact_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsors_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_contact_person_id'), ['contact_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsors_stage'), ['stage'], unique=False)

    op.create_table('finance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('amount_aud', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gst_included', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('date_requested', sa.Date(), nullable=True),
    sa.Column('date_paid', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('related_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['related_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_related_event_id'), ['related_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_type'), ['type'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_deleted'))
        batch_op.drop_index(batch_op.f('ix_event_notion_page_id'))
        batch_op.drop_index(batch_op.f('ix_event_status'))

    op.drop_table('event')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('notion_page_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('starts_at', sa.DATETIME(), nullable=True),
    sa.Column('ends_at', sa.DATETIME(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=512), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('synced_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_notion_page_id'), ['notion_page_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_event_deleted'), ['deleted'], unique=False)

    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_type'))
        batch_op.drop_index(batch_op.f('ix_finance_status'))
        batch_op.drop_index(batch_op.f('ix_finance_related_event_id'))
        batch_op.drop_index(batch_op.f('ix_finance_archived'))

    op.drop_table('finance')
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsors_stage'))
        batch_op.drop_index(batch_op.f('ix_sponsors_contact_person_id'))
        batch_op.drop_index(batch_op.f('ix_sponsors_archived'))

    op.drop_table('sponsors')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_start_date'))
        batch_op.drop_index(batch_op.f('ix_events_event_lead_id'))
        batch_op.drop_index(batch_op.f('ix_events_dusa_submission_status'))
        batch_op.drop_index(batch_op.f('ix_events_dusa_deadline'))
        batch_op.drop_index(batch_op.f('ix_events_archived'))

    op.drop_table('events')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_type'))
        batch_op.drop_index(batch_op.f('ix_people_status'))
        batch_op.drop_index(batch_op.f('ix_people_committee'))
        batch_op.drop_index(batch_op.f('ix_people_archived'))

    op.drop_table('people')
    # ### end Alembic commands ###
