"""baseline schema: EventLog APIKey RateLimit Event

Revision ID: 7b59509e3c76
Revises: 
Create Date: 2026-06-13 21:21:50.534825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b59509e3c76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('prefix', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=512), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_prefix'), ['prefix'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_key_revoked'), ['revoked'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_notion_page_id'), ['notion_page_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_status'), ['status'], unique=False)

    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('sender', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('classification', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_log_source'), ['source'], unique=False)

    op.create_table('rate_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.Column('bucket', sa.String(length=128), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('trigger_count_today', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['api_key.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id', 'window_start', name='uq_ratelimit_key_window')
    )
    with op.batch_alter_table('rate_limit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_bucket'), ['bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_key_id'), ['key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_window_start'), ['window_start'], unique=False)
        batch_op.create_index('ix_ratelimit_key_window', ['key_id', 'window_start'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_limit', schema=None) as batch_op:
        batch_op.drop_index('ix_ratelimit_key_window')
        batch_op.drop_index(batch_op.f('ix_rate_limit_window_start'))
        batch_op.drop_index(batch_op.f('ix_rate_limit_key_id'))
        batch_op.drop_index(batch_op.f('ix_rate_limit_bucket'))

    op.drop_table('rate_limit')
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_log_source'))
        batch_op.drop_index(batch_op.f('ix_event_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_event_log_action'))

    op.drop_table('event_log')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_status'))
        batch_op.drop_index(batch_op.f('ix_event_notion_page_id'))
        batch_op.drop_index(batch_op.f('ix_event_deleted'))

    op.drop_table('event')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_revoked'))
        batch_op.drop_index(batch_op.f('ix_api_key_prefix'))

    op.drop_table('api_key')
    # ### end Alembic commands ###
