"""sponsor contacts, attachments, and support-type fields

Adds:
* `sponsor_contact` — individual people (linked or free-text) per sponsor.
* `attachment`       — uploaded PDFs/images (Supabase) for sponsors etc.
* `sponsors.support_types`  — JSON list of in-kind/financial support tags.
* `events.support_types`    — JSON list of partner-provided support tags.
* `events.partner_org`      — name of a non-financial collaboration partner.

HAND-WRITTEN (not autogenerated) — see the workspace_tables migration note:
live Neon carries RBAC objects created outside Alembic, so autogenerate would
emit DROPs. This migration only CREATEs/ADDs.

Revision ID: a1b2c3d4e5f6
Revises: f3a9d2b7c4e1
Create Date: 2026-06-15
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, Sequence[str], None] = "f3a9d2b7c4e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ts(name: str) -> sa.Column:
    return sa.Column(name, sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)


def _archived() -> sa.Column:
    return sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False)


def upgrade() -> None:
    # --- new support-type / partner columns (JSON defaults to an empty list) ---
    op.add_column("sponsors", sa.Column("support_types", sa.JSON(), nullable=True))
    op.add_column("events", sa.Column("support_types", sa.JSON(), nullable=True))
    op.add_column("events", sa.Column("partner_org", sa.String(length=256), nullable=True))

    # --- sponsor_contact -----------------------------------------------------
    op.create_table(
        "sponsor_contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sponsor_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("role", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        _ts("created_at"),
        _ts("updated_at"),
        _archived(),
        sa.ForeignKeyConstraint(["sponsor_id"], ["sponsors.id"], name="sponsor_contact_sponsor_id_fkey"),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], name="sponsor_contact_person_id_fkey"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sponsor_contact", schema=None) as b:
        b.create_index(b.f("ix_sponsor_contact_sponsor_id"), ["sponsor_id"], unique=False)
        b.create_index(b.f("ix_sponsor_contact_person_id"), ["person_id"], unique=False)
        b.create_index(b.f("ix_sponsor_contact_archived"), ["archived"], unique=False)

    # --- attachment ----------------------------------------------------------
    op.create_table(
        "attachment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=16), nullable=False),  # sponsor
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),  # image|pdf|file
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("original_filename", sa.String(length=512), nullable=True),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("original_size_bytes", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        _ts("created_at"),
        _ts("updated_at"),
        _archived(),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attachment", schema=None) as b:
        b.create_index("ix_attachment_entity", ["entity_type", "entity_id"], unique=False)
        b.create_index(b.f("ix_attachment_archived"), ["archived"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("attachment", schema=None) as b:
        b.drop_index(b.f("ix_attachment_archived"))
        b.drop_index("ix_attachment_entity")
    op.drop_table("attachment")

    with op.batch_alter_table("sponsor_contact", schema=None) as b:
        b.drop_index(b.f("ix_sponsor_contact_archived"))
        b.drop_index(b.f("ix_sponsor_contact_person_id"))
        b.drop_index(b.f("ix_sponsor_contact_sponsor_id"))
    op.drop_table("sponsor_contact")

    op.drop_column("events", "partner_org")
    op.drop_column("events", "support_types")
    op.drop_column("sponsors", "support_types")
