"""document related_task_id: link docs to tasks

Adds document.related_task_id, an optional FK to task.id — the same one-to-many
"related entity" pattern documents already use for events, sponsors, projects
and meetings. Lets a doc (a spec, brief, or notes) be attached to a task, and
surfaces those docs back on the task's edit page.

Idempotent: inspects the live schema first and only adds what's missing.

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Revision ID: a1d4f7b2e9c3
Revises: c4e8a2f6b9d1
Create Date: 2026-06-19
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "a1d4f7b2e9c3"
down_revision: Union[str, Sequence[str], None] = "c4e8a2f6b9d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def _indexes(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {ix["name"] for ix in insp.get_indexes(table)}


def _fks(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {fk["name"] for fk in insp.get_foreign_keys(table) if fk.get("name")}


def upgrade() -> None:
    if "related_task_id" not in _columns("document"):
        op.add_column("document", sa.Column("related_task_id", sa.Integer(), nullable=True))
        op.create_foreign_key(
            "fk_document_related_task_id_task",
            "document",
            "task",
            ["related_task_id"],
            ["id"],
        )
    if "ix_document_related_task_id" not in _indexes("document"):
        op.create_index("ix_document_related_task_id", "document", ["related_task_id"])


def downgrade() -> None:
    if "ix_document_related_task_id" in _indexes("document"):
        op.drop_index("ix_document_related_task_id", table_name="document")
    if "fk_document_related_task_id_task" in _fks("document"):
        op.drop_constraint("fk_document_related_task_id_task", "document", type_="foreignkey")
    if "related_task_id" in _columns("document"):
        op.drop_column("document", "related_task_id")
