"""scan_page: editable title/description header for the public /scan wall

Creates the `scan_page` singleton (always row id=1) carrying the heading shown
above the QR cards on dsec.club/scan — a big `title` and a one-line
`description`, both nullable (NULL ⇒ the built-in default copy). The QR cards
live in `scan_target` (migration d4f8b2c6a1e9); this only adds the header.

No seed row: the service returns a transient default when the row is absent and
the dashboard upserts id=1 on the first save (so a re-run never clobbers edits).

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.) Idempotent:
only creates the table if it is missing, so a re-run is safe.

Revision ID: a2e6c4f8b1d3
Revises: d4f8b2c6a1e9
Create Date: 2026-06-29
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "a2e6c4f8b1d3"
down_revision: Union[str, Sequence[str], None] = "d4f8b2c6a1e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(name: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(name)


def upgrade() -> None:
    if not _has_table("scan_page"):
        op.create_table(
            "scan_page",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("title", sa.String(length=120), nullable=True),
            sa.Column("description", sa.String(length=300), nullable=True),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            ),
        )


def downgrade() -> None:
    if _has_table("scan_page"):
        op.drop_table("scan_page")
