"""meeting.committee + document.committee: per-committee scoping

Adds a nullable `committee` tag to both `meeting` and `document` so meeting
notes (and their generated docs) can be scoped to a single committee. The
dsec-hub frontend enforces who can *see* a given committee's notes; this column
is the data carry-through that lets it filter.

  * NULL (default) — unscoped: visible per the existing rules
  * "<committee>"  — scoped: only that committee's members see it in dsec-hub

Existing rows keep NULL (unscoped), so this never hides anything that was
previously visible.

Idempotent: inspects the live schema first and only adds each column if missing
(the `meeting`/`document` tables were created earlier without it).

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Revision ID: a3f7c1e9d2b5
Revises: d9e2b6a4c1f8
Create Date: 2026-06-17
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "a3f7c1e9d2b5"
down_revision: Union[str, Sequence[str], None] = "d9e2b6a4c1f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def upgrade() -> None:
    if "committee" not in _columns("meeting"):
        op.add_column("meeting", sa.Column("committee", sa.String(length=128), nullable=True))
    if "committee" not in _columns("document"):
        op.add_column("document", sa.Column("committee", sa.String(length=128), nullable=True))


def downgrade() -> None:
    if "committee" in _columns("meeting"):
        op.drop_column("meeting", "committee")
    if "committee" in _columns("document"):
        op.drop_column("document", "committee")
