"""link tree: link + link_profile tables

Adds the DSEC LINK-TREE feature to the schema — a standalone, chromeless
"Linktree" page (dsec-website `/links`) the committee curates as the single link
in an Instagram/Discord bio:

  * link         — one tappable button (title, optional subtitle, destination
                   url, optional emoji icon, optional brand accent, an explicit
                   display_order, and an is_visible flag the PUBLIC feed filters
                   on). Soft-deleted via `archived` (indexed).
  * link_profile — the singleton page header (always row id=1): title, tagline
                   and mascot (a PixelDuck sprite name). Seeded with a single
                   default row only when the table is empty.

HAND-WRITTEN (not autogenerated) — live Neon carries RBAC / app-owned objects
created outside Alembic, so autogenerate would emit DROPs. This migration only
CREATEs against live Neon, never a drop on upgrade. (See the team rule against
`alembic --autogenerate` on Neon.) Idempotent: it inspects the live schema first
and only creates a table / index that is missing, and only seeds link_profile
when empty, so a re-run is safe.

Revision ID: a4e8c2f6d9b1
Revises: b9e1f4c7a3d2
Create Date: 2026-06-25
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "a4e8c2f6d9b1"
down_revision: Union[str, Sequence[str], None] = "b9e1f4c7a3d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ts(name: str) -> sa.Column:
    return sa.Column(name, sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)


def _tables() -> set[str]:
    return set(sa.inspect(op.get_bind()).get_table_names())


def upgrade() -> None:
    existing = _tables()

    # --- link ----------------------------------------------------------------
    if "link" not in existing:
        op.create_table(
            "link",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("title", sa.String(length=120), nullable=False),
            sa.Column("subtitle", sa.String(length=160), nullable=True),
            sa.Column("url", sa.String(length=2048), nullable=False),
            sa.Column("icon", sa.String(length=32), nullable=True),
            sa.Column("accent", sa.String(length=16), nullable=True),
            sa.Column("display_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
            sa.Column("is_visible", sa.Boolean(), server_default=sa.text("true"), nullable=False),
            _ts("created_at"),
            _ts("updated_at"),
            sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )

    # Create the archived index independently of the table-create branch so it is
    # added whenever missing (e.g. the table already exists from a partial run).
    link_indexes = {ix["name"] for ix in sa.inspect(op.get_bind()).get_indexes("link")}
    if "ix_link_archived" not in link_indexes:
        with op.batch_alter_table("link", schema=None) as b:
            b.create_index(b.f("ix_link_archived"), ["archived"], unique=False)

    # --- link_profile (singleton header — always row id=1) -------------------
    if "link_profile" not in existing:
        op.create_table(
            "link_profile",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("title", sa.String(length=60), server_default=sa.text("'DSEC'"), nullable=False),
            sa.Column("tagline", sa.String(length=160), nullable=True),
            sa.Column("mascot", sa.String(length=64), nullable=True),
            _ts("updated_at"),
            sa.PrimaryKeyConstraint("id"),
        )

    # Seed the singleton profile row (id=1) only if none exists yet, so a re-run
    # never clobbers committee edits.
    bind = op.get_bind()
    existing_profiles = bind.execute(sa.text("SELECT COUNT(*) FROM link_profile")).scalar()
    if not existing_profiles:
        link_profile = sa.table(
            "link_profile",
            sa.column("id", sa.Integer),
            sa.column("title", sa.String),
            sa.column("tagline", sa.String),
            sa.column("mascot", sa.String),
        )
        op.bulk_insert(
            link_profile,
            [{"id": 1, "title": "DSEC", "tagline": "Deakin Software Engineering Club",
              "mascot": "duck-mascot"}],
        )


def downgrade() -> None:
    if "link" in _tables():
        with op.batch_alter_table("link", schema=None) as b:
            b.drop_index(b.f("ix_link_archived"))
        op.drop_table("link")
    if "link_profile" in _tables():
        op.drop_table("link_profile")
