"""event speakers, event-sponsor links, and the sponsor website flag

Adds:
* `event_speaker`  — speakers per event (linked person or free-text guest).
                     Headshots reuse `media_asset` (entity_type="speaker").
* `event_sponsor`  — many-to-many event<->sponsor so an event can show a wall of
                     sponsor logos. Logos reuse `media_asset` (entity_type="sponsor",
                     role="logo").
* `sponsors.show_on_website` — publish a confirmed sponsor + logo on the public site.

`media_asset` needs NO schema change — its entity_type/role are free varchars, so
"sponsor"/"speaker" and "logo"/"photo" are validated only in the app layer.

HAND-WRITTEN (not autogenerated) — live Neon carries RBAC objects created outside
Alembic, so autogenerate would emit DROPs. This migration only CREATEs/ADDs.

Revision ID: a7c1e9f2b3d4
Revises: f4b9c1d3e5a7
Create Date: 2026-06-15
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "a7c1e9f2b3d4"
down_revision: Union[str, Sequence[str], None] = "f4b9c1d3e5a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ts(name: str) -> sa.Column:
    return sa.Column(name, sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)


def _archived() -> sa.Column:
    return sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False)


def upgrade() -> None:
    # --- sponsors.show_on_website -------------------------------------------
    op.add_column(
        "sponsors",
        sa.Column("show_on_website", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )

    # --- event_speaker -------------------------------------------------------
    op.create_table(
        "event_speaker",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        _ts("created_at"),
        _ts("updated_at"),
        _archived(),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], name="event_speaker_event_id_fkey"),
        sa.ForeignKeyConstraint(["person_id"], ["people.id"], name="event_speaker_person_id_fkey"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("event_speaker", schema=None) as b:
        b.create_index(b.f("ix_event_speaker_event_id"), ["event_id"], unique=False)
        b.create_index(b.f("ix_event_speaker_person_id"), ["person_id"], unique=False)
        b.create_index(b.f("ix_event_speaker_archived"), ["archived"], unique=False)

    # --- event_sponsor -------------------------------------------------------
    op.create_table(
        "event_sponsor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("sponsor_id", sa.Integer(), nullable=False),
        sa.Column("tier", sa.String(length=64), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        _ts("created_at"),
        _ts("updated_at"),
        _archived(),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], name="event_sponsor_event_id_fkey"),
        sa.ForeignKeyConstraint(["sponsor_id"], ["sponsors.id"], name="event_sponsor_sponsor_id_fkey"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "sponsor_id", name="uq_event_sponsor"),
    )
    with op.batch_alter_table("event_sponsor", schema=None) as b:
        b.create_index(b.f("ix_event_sponsor_event_id"), ["event_id"], unique=False)
        b.create_index(b.f("ix_event_sponsor_sponsor_id"), ["sponsor_id"], unique=False)
        b.create_index(b.f("ix_event_sponsor_archived"), ["archived"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("event_sponsor", schema=None) as b:
        b.drop_index(b.f("ix_event_sponsor_archived"))
        b.drop_index(b.f("ix_event_sponsor_sponsor_id"))
        b.drop_index(b.f("ix_event_sponsor_event_id"))
    op.drop_table("event_sponsor")

    with op.batch_alter_table("event_speaker", schema=None) as b:
        b.drop_index(b.f("ix_event_speaker_archived"))
        b.drop_index(b.f("ix_event_speaker_person_id"))
        b.drop_index(b.f("ix_event_speaker_event_id"))
    op.drop_table("event_speaker")

    op.drop_column("sponsors", "show_on_website")
