"""event is_public: draft vs published

Adds events.is_public, the draft/published flag that gates the public website
feed (/website/events now filters is_public=True). Mirrors project.is_public:
  * False (default) — draft: created in the dashboard, hidden from the website
  * True            — published: live on the public site

A new event starts as a draft. Existing events are BACKFILLED to published so
this change never silently pulls events that are already live off the website;
the team can unpublish any stale ones from the dashboard afterwards.

Idempotent: inspects the live schema first and only adds what's missing.

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Revision ID: a9f3c1e7d2b4
Revises: c5a7e9f1b3d6
Create Date: 2026-06-16
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "a9f3c1e7d2b4"
down_revision: Union[str, Sequence[str], None] = "c5a7e9f1b3d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def _indexes(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {ix["name"] for ix in insp.get_indexes(table)}


def upgrade() -> None:
    if "is_public" not in _columns("events"):
        op.add_column(
            "events",
            sa.Column(
                "is_public",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            ),
        )
        # Preserve current visibility: everything that exists today stays live.
        # New events created after this migration default to draft (false).
        op.execute("UPDATE events SET is_public = true")
    if "ix_events_is_public" not in _indexes("events"):
        op.create_index("ix_events_is_public", "events", ["is_public"])


def downgrade() -> None:
    if "ix_events_is_public" in _indexes("events"):
        op.drop_index("ix_events_is_public", table_name="events")
    if "is_public" in _columns("events"):
        op.drop_column("events", "is_public")
