"""rate_limit: make the unique key bucket-aware + NULLS NOT DISTINCT

The old unique key was (key_id, window_start), excluding `bucket`. Two problems
that fix cleanly together:

1. A request at exactly 00:00 UTC creates a per-minute row (bucket='req') and a
   per-day trigger row (bucket='trigger') that share window_start=midnight — they
   collided under the old key. Adding `bucket` separates them.
2. Per-IP rows carry key_id=NULL, and Postgres treats NULLs as DISTINCT in a
   unique index, so two concurrent first-of-window per-IP requests could both
   insert and split the counter into duplicate rows. NULLS NOT DISTINCT (PG15+)
   makes them collide, so the limiter's insert/on-conflict path converges.

HAND-WRITTEN (never autogenerated against Neon — see the team rule). Idempotent
and Postgres-only: on any other dialect it is a no-op, because SQLite dev builds
the schema from the models + stamps head and never replays this chain.

Revision ID: b1d4f7a9c3e2
Revises: a2e6c4f8b1d3
Create Date: 2026-08-29
"""
from typing import Sequence, Union

from alembic import op

revision: str = "b1d4f7a9c3e2"
down_revision: Union[str, Sequence[str], None] = "a2e6c4f8b1d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_OLD_CONSTRAINT = "uq_ratelimit_key_window"
_NEW_INDEX = "uq_ratelimit_key_bucket_window"

# Fold duplicate (key_id, bucket, window_start) rows into the lowest id, summing
# both counters, then delete the extras — so the new unique index can be built.
# GROUP BY / PARTITION BY fold NULL key_ids together, matching NULLS NOT DISTINCT.
_DEDUPE_SQL = """
UPDATE rate_limit r SET
    count = agg.sum_count,
    trigger_count_today = agg.sum_trigger
FROM (
    SELECT MIN(id) AS keep_id,
           SUM(count) AS sum_count,
           SUM(trigger_count_today) AS sum_trigger
    FROM rate_limit
    GROUP BY key_id, bucket, window_start
    HAVING COUNT(*) > 1
) agg
WHERE r.id = agg.keep_id;

DELETE FROM rate_limit r
USING (
    SELECT id,
           MIN(id) OVER (PARTITION BY key_id, bucket, window_start) AS keep_id
    FROM rate_limit
) d
WHERE r.id = d.id AND d.id <> d.keep_id;
"""


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    if not _is_postgres():
        return
    import sqlalchemy as sa

    bind = op.get_bind()

    # Collapse any duplicate rows the old key allowed.
    op.execute(_DEDUPE_SQL)

    # Drop the old (key_id, window_start) unique constraint.
    op.execute(f"ALTER TABLE rate_limit DROP CONSTRAINT IF EXISTS {_OLD_CONSTRAINT}")

    # NULLS NOT DISTINCT needs PG15+. Fall back to a plain bucket-aware unique
    # index on older servers (still fixes problem 1; problem 2 stays mitigated by
    # the limiter's order-by-id read).
    version_num = bind.execute(sa.text("SHOW server_version_num")).scalar()
    nulls_clause = " NULLS NOT DISTINCT" if int(version_num) >= 150000 else ""
    op.execute(
        f"CREATE UNIQUE INDEX IF NOT EXISTS {_NEW_INDEX} "
        f"ON rate_limit (key_id, bucket, window_start){nulls_clause}"
    )


# Fold rows to one per (key_id, window_start) so the OLD constraint can be
# re-added. The new key allowed two rows (bucket='req' and 'trigger') that share
# window_start=midnight for the same key; the old key forbids them, so the
# downgrade must collapse them first or the ADD CONSTRAINT would fail on live
# data. Counters are transient (windows expire), so summing is safe.
_DOWNGRADE_DEDUPE_SQL = """
UPDATE rate_limit r SET
    count = agg.sum_count,
    trigger_count_today = agg.sum_trigger
FROM (
    SELECT MIN(id) AS keep_id,
           SUM(count) AS sum_count,
           SUM(trigger_count_today) AS sum_trigger
    FROM rate_limit
    GROUP BY key_id, window_start
    HAVING COUNT(*) > 1
) agg
WHERE r.id = agg.keep_id;

DELETE FROM rate_limit r
USING (
    SELECT id,
           MIN(id) OVER (PARTITION BY key_id, window_start) AS keep_id
    FROM rate_limit
) d
WHERE r.id = d.id AND d.id <> d.keep_id;
"""


def downgrade() -> None:
    if not _is_postgres():
        return
    op.execute(f"DROP INDEX IF EXISTS {_NEW_INDEX}")
    # Collapse cross-bucket collisions the new key allowed, so re-adding the old
    # (key_id, window_start) unique constraint cannot fail on populated data.
    op.execute(_DOWNGRADE_DEDUPE_SQL)
    op.execute(
        f"ALTER TABLE rate_limit ADD CONSTRAINT {_OLD_CONSTRAINT} "
        f"UNIQUE (key_id, window_start)"
    )
