"""sponsor relationship_type + event related_sponsor_id link

Follow-up to a1b2c3d4e5f6. These two columns were added to the models after the
prior migration had already been applied to live Neon, so Alembic would not
re-run it. This migration adds them on their own.

Idempotent: it checks the live schema first and only adds what's missing, so it
applies cleanly whether or not an environment already received these columns via
an earlier copy of the prior migration.

HAND-WRITTEN (not autogenerated) — only CREATEs/ADDs against live Neon.

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-06-15
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "b2c3d4e5f6a7"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def upgrade() -> None:
    sponsor_cols = _columns("sponsors")
    if "relationship_type" not in sponsor_cols:
        op.add_column(
            "sponsors", sa.Column("relationship_type", sa.String(length=32), nullable=True)
        )

    event_cols = _columns("events")
    if "related_sponsor_id" not in event_cols:
        op.add_column("events", sa.Column("related_sponsor_id", sa.Integer(), nullable=True))
        with op.batch_alter_table("events", schema=None) as b:
            b.create_index(
                b.f("ix_events_related_sponsor_id"), ["related_sponsor_id"], unique=False
            )
            b.create_foreign_key(
                "events_related_sponsor_id_fkey", "sponsors", ["related_sponsor_id"], ["id"]
            )


def downgrade() -> None:
    event_cols = _columns("events")
    if "related_sponsor_id" in event_cols:
        with op.batch_alter_table("events", schema=None) as b:
            b.drop_constraint("events_related_sponsor_id_fkey", type_="foreignkey")
            b.drop_index(b.f("ix_events_related_sponsor_id"))
        op.drop_column("events", "related_sponsor_id")

    sponsor_cols = _columns("sponsors")
    if "relationship_type" in sponsor_cols:
        op.drop_column("sponsors", "relationship_type")
