"""rename events.notes -> events.description

The event "notes" field is being repurposed as a public, Markdown-rendered
event description (shown on the dsec-website detail page). Same column, same
data — just a clearer name. A plain RENAME COLUMN preserves existing values.

HAND-WRITTEN (not autogenerated) — live Neon carries RBAC objects created
outside Alembic, so autogenerate would emit DROPs. This migration only renames.

Revision ID: b2d4f6a8c1e3
Revises: a7c1e9f2b3d4
Create Date: 2026-06-15
"""
from typing import Sequence, Union

from alembic import op

revision: str = "b2d4f6a8c1e3"
down_revision: Union[str, Sequence[str], None] = "a7c1e9f2b3d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column("events", "notes", new_column_name="description")


def downgrade() -> None:
    op.alter_column("events", "description", new_column_name="notes")
