"""project review workflow — submission + moderation columns and the public gate (SHOW-5)

Adds the moderation workflow to ``project``: a ``source`` (committee vs. member
portal), a ``review_state`` (draft / pending / approved / rejected, indexed for the
queue), the submitter soft-link + email + timestamp, reviewer/internal notes, and
who reviewed it and when. None are FKs — the submitter's account lives in a table
this service does not own.

The gate is a CHECK: ``is_public = false OR review_state = 'approved'`` — nothing
reaches the public website unless a human has approved it.

⚠️ COUPLED DEPLOY. dsec-hub's ``setProjectPublished`` currently flips ``is_public``
true while ``review_state`` is still 'draft'. The instant this CHECK is live, that
write violates it and the committee's publish button 500s. This migration MUST
land in the same deploy window as the dsec-hub change (SHOW-6) that sets
``review_state='approved'`` in the same statement as ``is_public=true``. Deploy the
API (this migration) FIRST, then the hub. Take a Neon backup before deploying.

Backfill order matters: every pre-existing row gets ``review_state='draft'`` from
the server_default, so the already-public rows are flipped to 'approved' BEFORE the
CHECK is added — otherwise adding the constraint would fail on them.

HAND-WRITTEN (never autogenerated against Neon — the same DB carries independent
Drizzle schemas autogenerate would try to "fix"). The SQLite dev/test schema is
built from the models + stamped head and never replays this chain, so this file is
Postgres-only (partial index, ADD CONSTRAINT CHECK).

Revision ID: b3d9f1c05a72
Revises: f1d5b8c3a6e9
Create Date: 2026-08-30
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "b3d9f1c05a72"
down_revision: Union[str, Sequence[str], None] = "f1d5b8c3a6e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_QUEUE_INDEX = "ix_project_review_queue"
_STATE_INDEX = "ix_project_review_state"
_CHECK = "ck_project_public_requires_approved"

# (name, column) for the additive columns. server_default keeps every pre-existing
# row valid without a separate UPDATE for the NOT NULL ones.
_COLUMNS: list[tuple[str, sa.Column]] = [
    ("source", sa.Column("source", sa.String(length=32), nullable=False, server_default="committee")),
    ("review_state", sa.Column("review_state", sa.String(length=16), nullable=False, server_default="draft")),
    ("submitted_by_account_id", sa.Column("submitted_by_account_id", sa.Integer(), nullable=True)),
    ("submitted_by_email", sa.Column("submitted_by_email", sa.String(length=320), nullable=True)),
    ("submitted_at", sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True)),
    ("review_note", sa.Column("review_note", sa.Text(), nullable=True)),
    ("internal_note", sa.Column("internal_note", sa.Text(), nullable=True)),
    ("reviewed_by", sa.Column("reviewed_by", sa.String(length=320), nullable=True)),
    ("reviewed_by_account_id", sa.Column("reviewed_by_account_id", sa.Integer(), nullable=True)),
    ("reviewed_at", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True)),
]


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def _indexes(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {i["name"] for i in insp.get_indexes(table)}


def _checks(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c.get("name") for c in insp.get_check_constraints(table)}


def upgrade() -> None:
    existing = _columns("project")
    for name, column in _COLUMNS:
        if name not in existing:
            op.add_column("project", column)

    # Backfill: already-public rows are historically approved, so they satisfy the
    # CHECK below. Everything else keeps the 'draft' server_default. Idempotent.
    op.execute(
        sa.text(
            "UPDATE project SET review_state = 'approved' "
            "WHERE is_public = true AND review_state <> 'approved'"
        )
    )

    indexes = _indexes("project")
    if _STATE_INDEX not in indexes:
        op.create_index(_STATE_INDEX, "project", ["review_state"])
    # Partial index: the moderation queue only ever scans rows awaiting review.
    if _QUEUE_INDEX not in indexes:
        op.create_index(
            _QUEUE_INDEX,
            "project",
            ["review_state"],
            postgresql_where=sa.text("review_state = 'pending'"),
        )

    if _CHECK not in _checks("project"):
        op.create_check_constraint(
            _CHECK, "project", "is_public = false OR review_state = 'approved'"
        )


def downgrade() -> None:
    checks = _checks("project")
    if _CHECK in checks:
        op.drop_constraint(_CHECK, "project", type_="check")

    indexes = _indexes("project")
    if _QUEUE_INDEX in indexes:
        op.drop_index(_QUEUE_INDEX, table_name="project")
    if _STATE_INDEX in indexes:
        op.drop_index(_STATE_INDEX, table_name="project")

    existing = _columns("project")
    for name, _ in reversed(_COLUMNS):
        if name in existing:
            op.drop_column("project", name)
