"""co-owner join tables: task_owner, event_owner, project_owner

Adds the three "additional owner" join tables that let a task, event or project
be co-owned by several people. Each entity keeps its single PRIMARY owner on its
own row (task.assignee_id / events.event_lead_id / project.lead_id); these
tables hold only the extra owners, so the change is purely additive and every
existing query keeps working.

Each table: (id, <entity>_id, person_id, created_at) with UNIQUE(<entity>_id,
person_id) and ON DELETE CASCADE on both FKs.

Idempotent: inspects the live schema first and only creates what's missing.

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Revision ID: b6e9c2a4f1d7
Revises: a1d4f7b2e9c3
Create Date: 2026-06-19
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "b6e9c2a4f1d7"
down_revision: Union[str, Sequence[str], None] = "a1d4f7b2e9c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (join table, entity column, parent table) — structurally identical triplets.
_TABLES = (
    ("task_owner", "task_id", "task"),
    ("event_owner", "event_id", "events"),
    ("project_owner", "project_id", "project"),
)


def _table_names() -> set[str]:
    return set(sa.inspect(op.get_bind()).get_table_names())


def upgrade() -> None:
    existing = _table_names()
    for table, entity_col, parent in _TABLES:
        if table in existing:
            continue
        op.create_table(
            table,
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column(entity_col, sa.Integer(), nullable=False),
            sa.Column("person_id", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint([entity_col], [f"{parent}.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["person_id"], ["people.id"], ondelete="CASCADE"),
            sa.UniqueConstraint(entity_col, "person_id", name=f"uq_{table}"),
        )
        op.create_index(f"ix_{table}_{entity_col}", table, [entity_col])
        op.create_index(f"ix_{table}_person_id", table, ["person_id"])


def downgrade() -> None:
    existing = _table_names()
    for table, _entity_col, _parent in _TABLES:
        if table in existing:
            op.drop_table(table)
