"""oauth 2.1 server tables

Adds the three tables backing the MCP OAuth authorization server, so an MCP
client whose connector dialog only accepts a URL (e.g. Claude.ai) can log in +
approve instead of pasting a `dsec_live_` key:

* `oauth_client`    — dynamically-registered clients (RFC 7591). Mostly public
                      (PKCE, no secret); confidential clients store a hashed secret.
* `oauth_auth_code` — single-use, hashed, short-lived authorization codes (PKCE).
* `oauth_token`     — issued access tokens (+ rotating refresh tokens), opaque and
                      stored only as SHA-256 hashes, looked up by an indexed prefix.

HAND-WRITTEN (not autogenerated) — live Neon carries RBAC objects created outside
Alembic, so autogenerate would emit DROPs. This migration only CREATEs, and skips
any table that already exists so a re-run is safe.

Revision ID: b8d2f4a6c0e1
Revises: f1b3d5a7c9e2
Create Date: 2026-06-16
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "b8d2f4a6c0e1"
down_revision: Union[str, Sequence[str], None] = "f1b3d5a7c9e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ts(name: str, *, nullable: bool = False, server_default: bool = True) -> sa.Column:
    return sa.Column(
        name,
        sa.DateTime(timezone=True),
        server_default=sa.text("now()") if server_default else None,
        nullable=nullable,
    )


def _tables() -> set[str]:
    return set(sa.inspect(op.get_bind()).get_table_names())


def upgrade() -> None:
    existing = _tables()

    if "oauth_client" not in existing:
        op.create_table(
            "oauth_client",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("client_id", sa.String(length=64), nullable=False),
            sa.Column("client_secret_hash", sa.String(length=512), nullable=True),
            sa.Column("client_name", sa.String(length=256), nullable=True),
            sa.Column("redirect_uris", sa.JSON(), nullable=False),
            sa.Column("grant_types", sa.JSON(), nullable=False),
            sa.Column("response_types", sa.JSON(), nullable=False),
            sa.Column("scope", sa.String(length=256), nullable=True),
            sa.Column(
                "token_endpoint_auth_method",
                sa.String(length=32),
                server_default=sa.text("'none'"),
                nullable=False,
            ),
            _ts("created_at"),
            _ts("last_used_at", nullable=True, server_default=False),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("oauth_client", schema=None) as b:
            b.create_index(b.f("ix_oauth_client_client_id"), ["client_id"], unique=True)

    if "oauth_auth_code" not in existing:
        op.create_table(
            "oauth_auth_code",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("code_hash", sa.String(length=128), nullable=False),
            sa.Column("client_id", sa.String(length=64), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("redirect_uri", sa.String(length=1024), nullable=False),
            sa.Column("scope", sa.String(length=256), server_default=sa.text("''"), nullable=False),
            sa.Column("code_challenge", sa.String(length=256), nullable=False),
            sa.Column(
                "code_challenge_method",
                sa.String(length=8),
                server_default=sa.text("'S256'"),
                nullable=False,
            ),
            sa.Column("resource", sa.String(length=512), nullable=True),
            _ts("expires_at", server_default=False),
            sa.Column("consumed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
            _ts("created_at"),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("oauth_auth_code", schema=None) as b:
            b.create_index(b.f("ix_oauth_auth_code_code_hash"), ["code_hash"], unique=True)
            b.create_index(b.f("ix_oauth_auth_code_client_id"), ["client_id"], unique=False)
            b.create_index(b.f("ix_oauth_auth_code_user_id"), ["user_id"], unique=False)

    if "oauth_token" not in existing:
        op.create_table(
            "oauth_token",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("access_prefix", sa.String(length=32), nullable=False),
            sa.Column("access_token_hash", sa.String(length=128), nullable=False),
            sa.Column("refresh_prefix", sa.String(length=32), nullable=True),
            sa.Column("refresh_token_hash", sa.String(length=128), nullable=True),
            sa.Column("client_id", sa.String(length=64), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("scope", sa.String(length=256), server_default=sa.text("''"), nullable=False),
            sa.Column("resource", sa.String(length=512), nullable=True),
            _ts("access_expires_at", server_default=False),
            _ts("refresh_expires_at", nullable=True, server_default=False),
            sa.Column("revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
            _ts("created_at"),
            _ts("last_used_at", nullable=True, server_default=False),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("oauth_token", schema=None) as b:
            b.create_index(b.f("ix_oauth_token_access_prefix"), ["access_prefix"], unique=False)
            b.create_index(b.f("ix_oauth_token_access_token_hash"), ["access_token_hash"], unique=True)
            b.create_index(b.f("ix_oauth_token_refresh_prefix"), ["refresh_prefix"], unique=False)
            b.create_index(b.f("ix_oauth_token_refresh_token_hash"), ["refresh_token_hash"], unique=True)
            b.create_index(b.f("ix_oauth_token_client_id"), ["client_id"], unique=False)
            b.create_index(b.f("ix_oauth_token_user_id"), ["user_id"], unique=False)
            b.create_index(b.f("ix_oauth_token_revoked"), ["revoked"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("oauth_token", schema=None) as b:
        b.drop_index(b.f("ix_oauth_token_revoked"))
        b.drop_index(b.f("ix_oauth_token_user_id"))
        b.drop_index(b.f("ix_oauth_token_client_id"))
        b.drop_index(b.f("ix_oauth_token_refresh_token_hash"))
        b.drop_index(b.f("ix_oauth_token_refresh_prefix"))
        b.drop_index(b.f("ix_oauth_token_access_token_hash"))
        b.drop_index(b.f("ix_oauth_token_access_prefix"))
    op.drop_table("oauth_token")

    with op.batch_alter_table("oauth_auth_code", schema=None) as b:
        b.drop_index(b.f("ix_oauth_auth_code_user_id"))
        b.drop_index(b.f("ix_oauth_auth_code_client_id"))
        b.drop_index(b.f("ix_oauth_auth_code_code_hash"))
    op.drop_table("oauth_auth_code")

    with op.batch_alter_table("oauth_client", schema=None) as b:
        b.drop_index(b.f("ix_oauth_client_client_id"))
    op.drop_table("oauth_client")
