"""event flagship columns + flagship_signup table

Adds the FLAGSHIP marketing-event feature to the schema:

  * events.is_flagship / flagship_theme / flagship_state / flagship_teaser_title
    / flagship_teaser_body / flagship_reveal_at — a flagship event renders a
    unique dsec-website template with a secret `teaser` state and a `revealed`
    state. `is_flagship` mirrors events.is_public (boolean, server_default false,
    indexed); `flagship_theme` (default 'arena') / `flagship_state` (default
    'teaser') are short varchars with server defaults; the teaser copy is
    nullable text/varchar; `flagship_reveal_at` is a nullable timestamptz
    countdown target.
  * flagship_signup — the teaser-page email/sponsor funnel sink, with a UNIQUE
    (event_id, kind, email) so re-submits from the public form are idempotent.

HAND-WRITTEN (not autogenerated) — live Neon carries RBAC / app-owned objects
created outside Alembic, so autogenerate would emit DROPs. This migration only
ADDs/CREATEs against live Neon, never a drop on upgrade. (See the team rule
against `alembic --autogenerate` on Neon.) Idempotent: it inspects the live
schema first and only adds a column / index / table that is missing, so a re-run
is safe. New event columns carry server defaults, so existing rows backfill to
not-flagship (false / 'arena' / 'teaser') automatically.

Revision ID: b9e1f4c7a3d2
Revises: f7c2a9d4b1e6
Create Date: 2026-06-25
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "b9e1f4c7a3d2"
down_revision: Union[str, Sequence[str], None] = "f7c2a9d4b1e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def _indexes(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {ix["name"] for ix in insp.get_indexes(table)}


def _tables() -> set[str]:
    return set(sa.inspect(op.get_bind()).get_table_names())


def upgrade() -> None:
    # --- events flagship columns (each guarded individually) -----------------
    cols = _columns("events")

    if "is_flagship" not in cols:
        op.add_column(
            "events",
            sa.Column(
                "is_flagship",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            ),
        )
    if "flagship_theme" not in cols:
        op.add_column(
            "events",
            sa.Column(
                "flagship_theme",
                sa.String(length=16),
                server_default=sa.text("'arena'"),
                nullable=False,
            ),
        )
    if "flagship_state" not in cols:
        op.add_column(
            "events",
            sa.Column(
                "flagship_state",
                sa.String(length=16),
                server_default=sa.text("'teaser'"),
                nullable=False,
            ),
        )
    if "flagship_teaser_title" not in cols:
        op.add_column(
            "events",
            sa.Column("flagship_teaser_title", sa.String(length=256), nullable=True),
        )
    if "flagship_teaser_body" not in cols:
        op.add_column(
            "events", sa.Column("flagship_teaser_body", sa.Text(), nullable=True)
        )
    if "flagship_reveal_at" not in cols:
        op.add_column(
            "events",
            sa.Column("flagship_reveal_at", sa.DateTime(timezone=True), nullable=True),
        )

    if "ix_events_is_flagship" not in _indexes("events"):
        op.create_index("ix_events_is_flagship", "events", ["is_flagship"])

    # --- flagship_signup (teaser-page funnel sink) ---------------------------
    if "flagship_signup" not in _tables():
        op.create_table(
            "flagship_signup",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("event_id", sa.Integer(), nullable=False),
            sa.Column("kind", sa.String(length=16), nullable=False),  # notify|sponsor
            sa.Column("email", sa.String(length=320), nullable=False),
            sa.Column("name", sa.String(length=256), nullable=True),
            sa.Column("company", sa.String(length=256), nullable=True),
            sa.Column("message", sa.Text(), nullable=True),
            sa.Column("source", sa.String(length=64), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.Column(
                "archived",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(
                ["event_id"], ["events.id"], name="flagship_signup_event_id_fkey"
            ),
            sa.PrimaryKeyConstraint("id"),
            # Idempotent re-submits: one row per (event, kind, email).
            sa.UniqueConstraint(
                "event_id", "kind", "email", name="uq_flagship_signup"
            ),
        )
        with op.batch_alter_table("flagship_signup", schema=None) as b:
            b.create_index(b.f("ix_flagship_signup_event_id"), ["event_id"], unique=False)
            b.create_index(b.f("ix_flagship_signup_created_at"), ["created_at"], unique=False)
            b.create_index(b.f("ix_flagship_signup_archived"), ["archived"], unique=False)


def downgrade() -> None:
    if "flagship_signup" in _tables():
        op.drop_table("flagship_signup")

    if "ix_events_is_flagship" in _indexes("events"):
        op.drop_index("ix_events_is_flagship", table_name="events")

    cols = _columns("events")
    for name in (
        "flagship_reveal_at",
        "flagship_teaser_body",
        "flagship_teaser_title",
        "flagship_state",
        "flagship_theme",
        "is_flagship",
    ):
        if name in cols:
            op.drop_column("events", name)
