"""meeting agenda: pre-meeting agenda fields on the meeting table

Adds the pre-meeting agenda capability to `meeting` — distinct from the existing
post-meeting transcript/notes/action-items flow:

* agenda_items       (JSON)        — ordered list of agenda item dicts:
                                      {id, order, title, owner_person_id,
                                       duration_minutes, notes, related_task_id,
                                       related_event_id}
* agenda_status      (varchar 16)  — draft | shared | locked, default 'draft'
* agenda_shared_at   (timestamptz) — when the agenda was first shared (nullable)
* agenda_share_token (varchar 64)  — unguessable token for the public read-only
                                      /agenda/<token> view; unique, nullable

Idempotent: inspects the live schema first and only adds what's missing.

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Revision ID: c1a4e7b9f2d6
Revises: b6e9c2a4f1d7
Create Date: 2026-06-21
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "c1a4e7b9f2d6"
down_revision: Union[str, Sequence[str], None] = "b6e9c2a4f1d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def _indexes(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {ix["name"] for ix in insp.get_indexes(table)}


def upgrade() -> None:
    cols = _columns("meeting")
    if "agenda_items" not in cols:
        op.add_column("meeting", sa.Column("agenda_items", sa.JSON(), nullable=True))
    if "agenda_status" not in cols:
        op.add_column(
            "meeting",
            sa.Column(
                "agenda_status",
                sa.String(length=16),
                nullable=False,
                server_default="draft",
            ),
        )
    if "agenda_shared_at" not in cols:
        op.add_column(
            "meeting",
            sa.Column("agenda_shared_at", sa.DateTime(timezone=True), nullable=True),
        )
    if "agenda_share_token" not in cols:
        op.add_column(
            "meeting", sa.Column("agenda_share_token", sa.String(length=64), nullable=True)
        )
    # Unique index doubles as the lookup index for the public share view.
    if "ix_meeting_agenda_share_token" not in _indexes("meeting"):
        op.create_index(
            "ix_meeting_agenda_share_token",
            "meeting",
            ["agenda_share_token"],
            unique=True,
        )


def downgrade() -> None:
    if "ix_meeting_agenda_share_token" in _indexes("meeting"):
        op.drop_index("ix_meeting_agenda_share_token", table_name="meeting")
    cols = _columns("meeting")
    for col in ("agenda_share_token", "agenda_shared_at", "agenda_status", "agenda_items"):
        if col in cols:
            op.drop_column("meeting", col)
