"""events.ticket_tiers — tiered ticket pricing (DSEC / DUSA / general + custom)

Adds one nullable JSON column to `events`:
  * ticket_tiers — list of {"label": str, "price": float | None}; price 0 = free,
    null = unset/POA. The dashboard seeds three default tiers (DSEC member /
    DUSA member / general public) and allows custom rows. Surfaced on the public
    website event page while the event is upcoming (hidden once it's past).

Idempotent + HAND-WRITTEN (not autogenerated) — only ADDs against live Neon.

Revision ID: c3f7b1a9d2e4
Revises: b3d5f7a9c1e2
Create Date: 2026-06-15
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "c3f7b1a9d2e4"
down_revision: Union[str, Sequence[str], None] = "b3d5f7a9c1e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def upgrade() -> None:
    if "ticket_tiers" not in _columns("events"):
        op.add_column("events", sa.Column("ticket_tiers", sa.JSON(), nullable=True))


def downgrade() -> None:
    if "ticket_tiers" in _columns("events"):
        op.drop_column("events", "ticket_tiers")
