"""widen oauth scope columns to 1024

The space-delimited scope string stored on the three OAuth tables overflowed
`varchar(256)`: a full-access grant from Claude.ai (every coarse + per-module
read:/write: scope) is ~270 chars, so `POST /oauth/authorize` crashed with
`StringDataRightTruncation` when inserting `oauth_auth_code.scope`. The same
overflow waits on `oauth_token.scope` (token exchange) and `oauth_client.scope`
(dynamic client registration). Widen all three to 1024 — comfortable headroom as
the MCP catalog keeps adding modules.

HAND-WRITTEN (not autogenerated) — live Neon carries RBAC objects created outside
Alembic, so autogenerate would emit DROPs. This migration only ALTERs the three
scope columns (widening a varchar is a fast metadata-only change in Postgres and
never truncates existing data), so it is safe to re-run.

Revision ID: c4e8a2f6b9d1
Revises: a3f7c1e9d2b5
Create Date: 2026-06-19
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "c4e8a2f6b9d1"
down_revision: Union[str, Sequence[str], None] = "a3f7c1e9d2b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "oauth_client", "scope",
        existing_type=sa.String(length=256), type_=sa.String(length=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "oauth_auth_code", "scope",
        existing_type=sa.String(length=256), type_=sa.String(length=1024),
        existing_nullable=False, existing_server_default=sa.text("''"),
    )
    op.alter_column(
        "oauth_token", "scope",
        existing_type=sa.String(length=256), type_=sa.String(length=1024),
        existing_nullable=False, existing_server_default=sa.text("''"),
    )


def downgrade() -> None:
    # Narrowing back can truncate rows wider than 256; intentionally a no-op
    # widening is forward-only. (Left as ALTERs would fail on overlong scopes.)
    op.alter_column(
        "oauth_token", "scope",
        existing_type=sa.String(length=1024), type_=sa.String(length=256),
        existing_nullable=False, existing_server_default=sa.text("''"),
    )
    op.alter_column(
        "oauth_auth_code", "scope",
        existing_type=sa.String(length=1024), type_=sa.String(length=256),
        existing_nullable=False, existing_server_default=sa.text("''"),
    )
    op.alter_column(
        "oauth_client", "scope",
        existing_type=sa.String(length=1024), type_=sa.String(length=256),
        existing_nullable=True,
    )
