"""people website fields: bio, show_on_website, display_order

Lets a roster person be published on the public website's team/committee grid
(dsec-website pulls them from /website/team), with their uploaded headshot
(media_asset entity_type="person", role="photo"):
  * bio            — public one-line intro, distinct from internal `notes`
  * show_on_website — publish flag (off by default, mirrors sponsors.show_on_website)
  * display_order   — manual ordering on the public grid (lower first), then name

Idempotent: inspects the live schema first and only adds what's missing, so it
applies cleanly whether or not an environment already received some columns.

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Revision ID: c5a7e9f1b3d6
Revises: b2d4f6a8c1e3
Create Date: 2026-06-16
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "c5a7e9f1b3d6"
down_revision: Union[str, Sequence[str], None] = "b2d4f6a8c1e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def upgrade() -> None:
    cols = _columns("people")
    if "bio" not in cols:
        op.add_column("people", sa.Column("bio", sa.Text(), nullable=True))
    if "show_on_website" not in cols:
        op.add_column(
            "people",
            sa.Column(
                "show_on_website",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            ),
        )
    if "display_order" not in cols:
        op.add_column(
            "people",
            sa.Column(
                "display_order",
                sa.Integer(),
                nullable=False,
                server_default=sa.text("0"),
            ),
        )


def downgrade() -> None:
    cols = _columns("people")
    for name in ("display_order", "show_on_website", "bio"):
        if name in cols:
            op.drop_column("people", name)
