"""link_profile socials: instagram / discord / linkedin / github / email

Adds the club's canonical social links to the singleton `link_profile` row so
they're edited ONCE and served to every surface (the /links page, the website +
portal footers, the contact / scan / join pages) through the public link-tree
feed — one source of truth instead of hardcoded placeholders in each app.

Adds to the `link_profile` table:
  * instagram — absolute http(s) profile URL (NULL = not set, doesn't render)
  * discord   — absolute http(s) invite URL
  * linkedin  — absolute http(s) profile URL
  * github    — absolute http(s) profile/org URL
  * email     — a bare address (consumers build the mailto: link)

All nullable, no backfill: existing rows keep their current header and simply
have no socials until the committee fills them in via dsec-hub.

Idempotent: inspects the live schema first and only adds what's missing.

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Revision ID: c7e1a9f3b5d2
Revises: f4c8e2a1d9b7
Create Date: 2026-06-28
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "c7e1a9f3b5d2"
down_revision: Union[str, Sequence[str], None] = "f4c8e2a1d9b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def upgrade() -> None:
    cols = _columns("link_profile")
    for name in ("instagram", "discord", "linkedin", "github"):
        if name not in cols:
            op.add_column(
                "link_profile", sa.Column(name, sa.String(length=512), nullable=True)
            )
    if "email" not in cols:
        op.add_column(
            "link_profile", sa.Column("email", sa.String(length=254), nullable=True)
        )


def downgrade() -> None:
    cols = _columns("link_profile")
    for name in ("email", "github", "linkedin", "discord", "instagram"):
        if name in cols:
            op.drop_column("link_profile", name)
