"""dusa weekly imports: members + finance from email

Adds the tables that hold the weekly DUSA imports forwarded by the Gmail
Apps Script and parsed at POST /ingest/dusa:

    dusa_import          — one row per upload (dedup key + audit)
    members              — paid-membership roster (upserted by student_id)
    member_report        — weekly membership stats snapshot
    finance_report       — weekly P&L snapshot (headline balances)
    finance_transaction  — P&L ledger lines

HAND-WRITTEN (not autogenerated). The live Neon DB contains RBAC objects
(app_role / app_invite / app_user.role_id) created outside Alembic by the
dsec-app permissions work; autogenerate would emit DROPs for them. This
migration only CREATEs the new tables, so it is safe to apply on top of head.

Revision ID: c7e2a9f4b1d8
Revises: 6b410fb3dad4
Create Date: 2026-06-14
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c7e2a9f4b1d8"
down_revision: Union[str, Sequence[str], None] = "6b410fb3dad4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ts(name: str, **kw) -> sa.Column:
    return sa.Column(name, sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False, **kw)


def upgrade() -> None:
    # --- dusa_import ---------------------------------------------------------
    op.create_table(
        "dusa_import",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.String(length=256), nullable=False),
        sa.Column("report_type", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=True),
        sa.Column("sender", sa.String(length=512), nullable=True),
        sa.Column("subject", sa.String(length=1024), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="ok", nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("rows_ingested", sa.Integer(), nullable=True),
        _ts("created_at"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dusa_import", schema=None) as b:
        b.create_index(b.f("ix_dusa_import_message_id"), ["message_id"], unique=True)
        b.create_index(b.f("ix_dusa_import_report_type"), ["report_type"], unique=False)
        b.create_index(b.f("ix_dusa_import_status"), ["status"], unique=False)
        b.create_index(b.f("ix_dusa_import_created_at"), ["created_at"], unique=False)

    # --- members -------------------------------------------------------------
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.String(length=32), nullable=False),
        sa.Column("full_name", sa.String(length=256), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("campus", sa.String(length=128), nullable=True),
        sa.Column("faculty", sa.String(length=256), nullable=True),
        sa.Column("payment_option", sa.String(length=256), nullable=True),
        sa.Column("membership_type", sa.String(length=32), nullable=True),
        sa.Column("dusa_member", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("first_subscription_date", sa.Date(), nullable=True),
        sa.Column("last_paid_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        _ts("first_seen_at"),
        _ts("last_seen_at"),
        _ts("created_at"),
        _ts("updated_at"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("members", schema=None) as b:
        b.create_index(b.f("ix_members_student_id"), ["student_id"], unique=True)
        b.create_index(b.f("ix_members_email"), ["email"], unique=False)
        b.create_index(b.f("ix_members_membership_type"), ["membership_type"], unique=False)
        b.create_index(b.f("ix_members_dusa_member"), ["dusa_member"], unique=False)
        b.create_index(b.f("ix_members_end_date"), ["end_date"], unique=False)
        b.create_index(b.f("ix_members_is_current"), ["is_current"], unique=False)

    # --- member_report -------------------------------------------------------
    op.create_table(
        "member_report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("import_id", sa.Integer(), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=True),
        sa.Column("total_members", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("dusa_member_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("non_dusa_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("new_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("renewal_count", sa.Integer(), nullable=False, server_default="0"),
        _ts("created_at"),
        sa.ForeignKeyConstraint(["import_id"], ["dusa_import.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("member_report", schema=None) as b:
        b.create_index(b.f("ix_member_report_import_id"), ["import_id"], unique=False)
        b.create_index(b.f("ix_member_report_report_date"), ["report_date"], unique=False)

    # --- finance_report ------------------------------------------------------
    op.create_table(
        "finance_report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("import_id", sa.Integer(), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=True),
        sa.Column("fy_start", sa.Date(), nullable=True),
        sa.Column("opening_balance", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("total_income", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("total_expense", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("closing_balance", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("transaction_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        _ts("created_at"),
        sa.ForeignKeyConstraint(["import_id"], ["dusa_import.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("finance_report", schema=None) as b:
        b.create_index(b.f("ix_finance_report_import_id"), ["import_id"], unique=False)
        b.create_index(b.f("ix_finance_report_report_date"), ["report_date"], unique=False)
        b.create_index(b.f("ix_finance_report_is_current"), ["is_current"], unique=False)

    # --- finance_transaction -------------------------------------------------
    op.create_table(
        "finance_transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("posting_date", sa.Date(), nullable=True),
        sa.Column("document_no", sa.String(length=64), nullable=True),
        sa.Column("gl_account_no", sa.String(length=16), nullable=True),
        sa.Column("gl_account_name", sa.String(length=256), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("department_code", sa.String(length=16), nullable=True),
        sa.Column("club_code", sa.String(length=32), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("amount_abs", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=True),
        _ts("created_at"),
        sa.ForeignKeyConstraint(["report_id"], ["finance_report.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("finance_transaction", schema=None) as b:
        b.create_index(b.f("ix_finance_transaction_report_id"), ["report_id"], unique=False)
        b.create_index(b.f("ix_finance_transaction_posting_date"), ["posting_date"], unique=False)
        b.create_index(b.f("ix_finance_transaction_document_no"), ["document_no"], unique=False)
        b.create_index(b.f("ix_finance_transaction_gl_account_no"), ["gl_account_no"], unique=False)
        b.create_index(b.f("ix_finance_transaction_kind"), ["kind"], unique=False)


def downgrade() -> None:
    op.drop_table("finance_transaction")
    op.drop_table("finance_report")
    op.drop_table("member_report")
    op.drop_table("members")
    op.drop_table("dusa_import")
