"""people student_id + socials, and app_user.person_id link

Links a dsec-app login (`app_user`) to its roster record (`people`) via a new
nullable `person_id` FK, and adds self-managed fields to `people`:
  * student_id — optional DUSA student id, joins to the live `members` roster
  * discord / instagram / github / linkedin / website — social + portfolio links

Idempotent: inspects the live schema first and only adds what's missing, so it
applies cleanly whether or not an environment already received some columns.

HAND-WRITTEN (not autogenerated) — only CREATEs/ADDs against live Neon, never a
drop on upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Revision ID: c8f1e3a5b9d2
Revises: b2c3d4e5f6a7
Create Date: 2026-06-15
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "c8f1e3a5b9d2"
down_revision: Union[str, Sequence[str], None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


# people: column name -> SQLAlchemy type. Plain nullable adds, no defaults.
_PEOPLE_COLS = {
    "student_id": sa.String(length=32),
    "discord": sa.String(length=128),
    "instagram": sa.String(length=128),
    "github": sa.String(length=128),
    "linkedin": sa.String(length=256),
    "website": sa.String(length=256),
}


def upgrade() -> None:
    people_cols = _columns("people")
    for name, type_ in _PEOPLE_COLS.items():
        if name not in people_cols:
            op.add_column("people", sa.Column(name, type_, nullable=True))
    if "student_id" not in people_cols:
        with op.batch_alter_table("people", schema=None) as b:
            b.create_index(b.f("ix_people_student_id"), ["student_id"], unique=False)

    app_user_cols = _columns("app_user")
    if "person_id" not in app_user_cols:
        op.add_column("app_user", sa.Column("person_id", sa.Integer(), nullable=True))
        with op.batch_alter_table("app_user", schema=None) as b:
            b.create_index(b.f("ix_app_user_person_id"), ["person_id"], unique=False)
            b.create_foreign_key(
                "app_user_person_id_fkey", "people", ["person_id"], ["id"]
            )


def downgrade() -> None:
    app_user_cols = _columns("app_user")
    if "person_id" in app_user_cols:
        with op.batch_alter_table("app_user", schema=None) as b:
            b.drop_constraint("app_user_person_id_fkey", type_="foreignkey")
            b.drop_index(b.f("ix_app_user_person_id"))
        op.drop_column("app_user", "person_id")

    people_cols = _columns("people")
    if "student_id" in people_cols:
        with op.batch_alter_table("people", schema=None) as b:
            b.drop_index(b.f("ix_people_student_id"))
    for name in _PEOPLE_COLS:
        if name in people_cols:
            op.drop_column("people", name)
