"""meeting time: optional local start time on the meeting

Adds meeting.meeting_time — an optional "HH:MM" 24h local start time. Kept as a
separate nullable column (NOT folded into meeting_date) so the existing Date
column, its index, ordering and the upcoming-meeting date filters are untouched.

Idempotent: inspects the live schema first and only adds what's missing.

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Revision ID: d3b7f1a9c5e2
Revises: c1a4e7b9f2d6
Create Date: 2026-06-21
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "d3b7f1a9c5e2"
down_revision: Union[str, Sequence[str], None] = "c1a4e7b9f2d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def upgrade() -> None:
    if "meeting_time" not in _columns("meeting"):
        op.add_column("meeting", sa.Column("meeting_time", sa.String(length=8), nullable=True))


def downgrade() -> None:
    if "meeting_time" in _columns("meeting"):
        op.drop_column("meeting", "meeting_time")
