"""workspace: projects, boards, tasks, meetings, documents (+event budget, sponsor pipeline)

Adds the workspace tables that back the dashboard sections and the MCP server,
and extends two existing tables:

    project, task_board, task, meeting, document      (new)
    events += budget_aud, grant_aud                    (alter)
    sponsors += contact_email, website, next_action,
                next_action_date, last_contact_date    (alter)

HAND-WRITTEN (not autogenerated) — see the dusa_weekly_imports migration note:
live Neon carries RBAC objects created outside Alembic, so autogenerate would
emit DROPs. This migration only CREATEs/ADDs.

Revision ID: d4b8e1a6f29c
Revises: c7e2a9f4b1d8
Create Date: 2026-06-14
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "d4b8e1a6f29c"
down_revision: Union[str, Sequence[str], None] = "c7e2a9f4b1d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ts(name: str) -> sa.Column:
    return sa.Column(name, sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)


def _archived() -> sa.Column:
    return sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False)


def upgrade() -> None:
    # --- project -------------------------------------------------------------
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("slug", sa.String(length=256), nullable=True),
        sa.Column("summary", sa.String(length=512), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("tech_tags", sa.JSON(), nullable=True),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("repo_url", sa.String(length=512), nullable=True),
        sa.Column("demo_url", sa.String(length=512), nullable=True),
        sa.Column("image_url", sa.String(length=512), nullable=True),
        sa.Column("featured", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_public", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("related_event_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        _ts("created_at"),
        _ts("updated_at"),
        _archived(),
        sa.ForeignKeyConstraint(["lead_id"], ["people.id"]),
        sa.ForeignKeyConstraint(["related_event_id"], ["events.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project", schema=None) as b:
        b.create_index(b.f("ix_project_slug"), ["slug"], unique=True)
        b.create_index(b.f("ix_project_status"), ["status"], unique=False)
        b.create_index(b.f("ix_project_lead_id"), ["lead_id"], unique=False)
        b.create_index(b.f("ix_project_featured"), ["featured"], unique=False)
        b.create_index(b.f("ix_project_is_public"), ["is_public"], unique=False)
        b.create_index(b.f("ix_project_related_event_id"), ["related_event_id"], unique=False)
        b.create_index(b.f("ix_project_archived"), ["archived"], unique=False)

    # --- task_board ----------------------------------------------------------
    op.create_table(
        "task_board",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("committee", sa.String(length=128), nullable=True),
        sa.Column("columns", sa.JSON(), nullable=True),
        _ts("created_at"),
        _ts("updated_at"),
        _archived(),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task_board", schema=None) as b:
        b.create_index(b.f("ix_task_board_committee"), ["committee"], unique=False)
        b.create_index(b.f("ix_task_board_archived"), ["archived"], unique=False)

    # --- task ----------------------------------------------------------------
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("board_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=64), server_default="Backlog", nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=True),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column("committee", sa.String(length=128), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("related_event_id", sa.Integer(), nullable=True),
        sa.Column("related_project_id", sa.Integer(), nullable=True),
        sa.Column("related_sponsor_id", sa.Integer(), nullable=True),
        _ts("created_at"),
        _ts("updated_at"),
        _archived(),
        sa.ForeignKeyConstraint(["board_id"], ["task_board.id"]),
        sa.ForeignKeyConstraint(["assignee_id"], ["people.id"]),
        sa.ForeignKeyConstraint(["related_event_id"], ["events.id"]),
        sa.ForeignKeyConstraint(["related_project_id"], ["project.id"]),
        sa.ForeignKeyConstraint(["related_sponsor_id"], ["sponsors.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task", schema=None) as b:
        b.create_index(b.f("ix_task_board_id"), ["board_id"], unique=False)
        b.create_index(b.f("ix_task_status"), ["status"], unique=False)
        b.create_index(b.f("ix_task_priority"), ["priority"], unique=False)
        b.create_index(b.f("ix_task_assignee_id"), ["assignee_id"], unique=False)
        b.create_index(b.f("ix_task_committee"), ["committee"], unique=False)
        b.create_index(b.f("ix_task_start_date"), ["start_date"], unique=False)
        b.create_index(b.f("ix_task_due_date"), ["due_date"], unique=False)
        b.create_index(b.f("ix_task_related_event_id"), ["related_event_id"], unique=False)
        b.create_index(b.f("ix_task_related_project_id"), ["related_project_id"], unique=False)
        b.create_index(b.f("ix_task_related_sponsor_id"), ["related_sponsor_id"], unique=False)
        b.create_index(b.f("ix_task_archived"), ["archived"], unique=False)

    # --- meeting -------------------------------------------------------------
    op.create_table(
        "meeting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=True),
        sa.Column("meeting_date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=256), nullable=True),
        sa.Column("attendees", sa.JSON(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("action_items", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("related_event_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(length=256), nullable=True),
        _ts("created_at"),
        _ts("updated_at"),
        _archived(),
        sa.ForeignKeyConstraint(["related_event_id"], ["events.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("meeting", schema=None) as b:
        b.create_index(b.f("ix_meeting_type"), ["type"], unique=False)
        b.create_index(b.f("ix_meeting_meeting_date"), ["meeting_date"], unique=False)
        b.create_index(b.f("ix_meeting_status"), ["status"], unique=False)
        b.create_index(b.f("ix_meeting_related_event_id"), ["related_event_id"], unique=False)
        b.create_index(b.f("ix_meeting_archived"), ["archived"], unique=False)

    # --- document ------------------------------------------------------------
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("content_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column("related_event_id", sa.Integer(), nullable=True),
        sa.Column("related_sponsor_id", sa.Integer(), nullable=True),
        sa.Column("related_project_id", sa.Integer(), nullable=True),
        sa.Column("related_meeting_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(length=256), nullable=True),
        _ts("created_at"),
        _ts("updated_at"),
        _archived(),
        sa.ForeignKeyConstraint(["parent_id"], ["document.id"]),
        sa.ForeignKeyConstraint(["assignee_id"], ["people.id"]),
        sa.ForeignKeyConstraint(["related_event_id"], ["events.id"]),
        sa.ForeignKeyConstraint(["related_sponsor_id"], ["sponsors.id"]),
        sa.ForeignKeyConstraint(["related_project_id"], ["project.id"]),
        sa.ForeignKeyConstraint(["related_meeting_id"], ["meeting.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document", schema=None) as b:
        b.create_index(b.f("ix_document_type"), ["type"], unique=False)
        b.create_index(b.f("ix_document_status"), ["status"], unique=False)
        b.create_index(b.f("ix_document_parent_id"), ["parent_id"], unique=False)
        b.create_index(b.f("ix_document_assignee_id"), ["assignee_id"], unique=False)
        b.create_index(b.f("ix_document_related_event_id"), ["related_event_id"], unique=False)
        b.create_index(b.f("ix_document_related_sponsor_id"), ["related_sponsor_id"], unique=False)
        b.create_index(b.f("ix_document_related_project_id"), ["related_project_id"], unique=False)
        b.create_index(b.f("ix_document_related_meeting_id"), ["related_meeting_id"], unique=False)
        b.create_index(b.f("ix_document_archived"), ["archived"], unique=False)

    # --- extend events + sponsors -------------------------------------------
    with op.batch_alter_table("events", schema=None) as b:
        b.add_column(sa.Column("budget_aud", sa.Numeric(precision=12, scale=2), nullable=True))
        b.add_column(sa.Column("grant_aud", sa.Numeric(precision=12, scale=2), nullable=True))

    with op.batch_alter_table("sponsors", schema=None) as b:
        b.add_column(sa.Column("contact_email", sa.String(length=256), nullable=True))
        b.add_column(sa.Column("website", sa.String(length=256), nullable=True))
        b.add_column(sa.Column("next_action", sa.String(length=512), nullable=True))
        b.add_column(sa.Column("next_action_date", sa.Date(), nullable=True))
        b.add_column(sa.Column("last_contact_date", sa.Date(), nullable=True))
        b.create_index(b.f("ix_sponsors_next_action_date"), ["next_action_date"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("sponsors", schema=None) as b:
        b.drop_index(b.f("ix_sponsors_next_action_date"))
        b.drop_column("last_contact_date")
        b.drop_column("next_action_date")
        b.drop_column("next_action")
        b.drop_column("website")
        b.drop_column("contact_email")
    with op.batch_alter_table("events", schema=None) as b:
        b.drop_column("grant_aud")
        b.drop_column("budget_aud")
    op.drop_table("document")
    op.drop_table("meeting")
    op.drop_table("task")
    op.drop_table("task_board")
    op.drop_table("project")
