"""scan_target: editable QR cards for the public /scan page

Creates the `scan_target` table — the committee-curated QR wall shown on
dsec.club/scan (built to put up on a screen at events). Mirrors the link-tree's
`link` table but QR-shaped: label, caption, url (the QR encodes it), pretty (the
short display under the QR), accent (blue/pink/yellow/mint or NULL=auto-cycle),
display_order, is_visible, archived.

Deliberately NO seed rows (unlike the link-tree migration, which seeds a profile
singleton): /scan has no default set — it renders exactly the visible rows here
plus the club's Instagram/Discord (auto-pulled from the link-profile socials).

Idempotent: only creates the table + index if absent.

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Revision ID: d4f8b2c6a1e9
Revises: c7e1a9f3b5d2
Create Date: 2026-06-28
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "d4f8b2c6a1e9"
down_revision: Union[str, Sequence[str], None] = "c7e1a9f3b5d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(name: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(name)


def _indexes(table: str) -> set[str]:
    return {ix["name"] for ix in sa.inspect(op.get_bind()).get_indexes(table)}


def upgrade() -> None:
    if not _has_table("scan_target"):
        op.create_table(
            "scan_target",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column("label", sa.String(length=120), nullable=False),
            sa.Column("caption", sa.String(length=200), nullable=True),
            sa.Column("url", sa.String(length=2048), nullable=False),
            sa.Column("pretty", sa.String(length=120), nullable=True),
            sa.Column("accent", sa.String(length=16), nullable=True),
            sa.Column(
                "display_order", sa.Integer(), nullable=False, server_default=sa.text("0")
            ),
            sa.Column(
                "is_visible", sa.Boolean(), nullable=False, server_default=sa.text("true")
            ),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            ),
            sa.Column(
                "archived", sa.Boolean(), nullable=False, server_default=sa.text("false")
            ),
        )

    if "ix_scan_target_archived" not in _indexes("scan_target"):
        op.create_index("ix_scan_target_archived", "scan_target", ["archived"])


def downgrade() -> None:
    if _has_table("scan_target"):
        if "ix_scan_target_archived" in _indexes("scan_target"):
            op.drop_index("ix_scan_target_archived", table_name="scan_target")
        op.drop_table("scan_target")
