"""app_user per-user theme preferences (accent colour + title/body fonts)

Adds three nullable, self-managed columns to `app_user`:
  * theme_accent     — accent/primary colour as a #RRGGBB hex (null = brand default)
  * theme_font_title — chosen heading font key, e.g. "geist-mono" (null = default)
  * theme_font_body  — chosen body font key, e.g. "inter" (null = default)

Owned by dsec-app (set via the Appearance settings tab); dsec-api never reads
them, but the column lives on the shared `app_user` table so it's migrated here.

Idempotent + HAND-WRITTEN (not autogenerated) — only ADDs against live Neon.

Revision ID: d5e6f7a8b9c0
Revises: c8f1e3a5b9d2
Create Date: 2026-06-15
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "d5e6f7a8b9c0"
down_revision: Union[str, Sequence[str], None] = "c8f1e3a5b9d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


_COLS = {
    "theme_accent": sa.String(length=16),
    "theme_font_title": sa.String(length=32),
    "theme_font_body": sa.String(length=32),
}


def upgrade() -> None:
    cols = _columns("app_user")
    for name, type_ in _COLS.items():
        if name not in cols:
            op.add_column("app_user", sa.Column(name, type_, nullable=True))


def downgrade() -> None:
    cols = _columns("app_user")
    for name in _COLS:
        if name in cols:
            op.drop_column("app_user", name)
