"""partners + event_partner links

Adds a first-class, lightweight **Partner** entity — a collaborator club /
society / external organisation that co-hosts events. Unlike `sponsors`, a
partner carries NO pipeline (no stage / value / packages); it is just a name,
website, notes, and an uploadable logo.

* `partner`        — the entity. Logo reuses `media_asset`
                     (entity_type="partner", role="logo").
* `event_partner`  — many-to-many event<->partner so an event can list the
                     clubs it is run in collaboration with. Internal-only for
                     now (not exposed on the public website).

`media_asset` needs NO schema change — its entity_type/role are free varchars,
so "partner"/"logo" are validated only in the app layer (see media/schemas.py).

HAND-WRITTEN (not autogenerated) — live Neon carries RBAC objects created outside
Alembic, so autogenerate would emit DROPs. This migration only CREATEs, and
skips a table that already exists so a re-run is safe.

Revision ID: d7e3b1f9a2c5
Revises: a9f3c1e7d2b4
Create Date: 2026-06-16
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "d7e3b1f9a2c5"
down_revision: Union[str, Sequence[str], None] = "a9f3c1e7d2b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ts(name: str) -> sa.Column:
    return sa.Column(name, sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)


def _archived() -> sa.Column:
    return sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False)


def _tables() -> set[str]:
    return set(sa.inspect(op.get_bind()).get_table_names())


def upgrade() -> None:
    existing = _tables()

    # --- partner -------------------------------------------------------------
    if "partner" not in existing:
        op.create_table(
            "partner",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=256), nullable=False),
            sa.Column("website", sa.String(length=256), nullable=True),
            sa.Column("notes", sa.Text(), nullable=True),
            _ts("created_at"),
            _ts("updated_at"),
            _archived(),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("partner", schema=None) as b:
            b.create_index(b.f("ix_partner_archived"), ["archived"], unique=False)

    # --- event_partner -------------------------------------------------------
    if "event_partner" not in existing:
        op.create_table(
            "event_partner",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("event_id", sa.Integer(), nullable=False),
            sa.Column("partner_id", sa.Integer(), nullable=False),
            # Optional per-event label, e.g. "Co-host" / "Supported by".
            sa.Column("role", sa.String(length=64), nullable=True),
            sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
            _ts("created_at"),
            _ts("updated_at"),
            _archived(),
            sa.ForeignKeyConstraint(["event_id"], ["events.id"], name="event_partner_event_id_fkey"),
            sa.ForeignKeyConstraint(["partner_id"], ["partner.id"], name="event_partner_partner_id_fkey"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("event_id", "partner_id", name="uq_event_partner"),
        )
        with op.batch_alter_table("event_partner", schema=None) as b:
            b.create_index(b.f("ix_event_partner_event_id"), ["event_id"], unique=False)
            b.create_index(b.f("ix_event_partner_partner_id"), ["partner_id"], unique=False)
            b.create_index(b.f("ix_event_partner_archived"), ["archived"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("event_partner", schema=None) as b:
        b.drop_index(b.f("ix_event_partner_archived"))
        b.drop_index(b.f("ix_event_partner_partner_id"))
        b.drop_index(b.f("ix_event_partner_event_id"))
    op.drop_table("event_partner")

    with op.batch_alter_table("partner", schema=None) as b:
        b.drop_index(b.f("ix_partner_archived"))
    op.drop_table("partner")
