"""api_key.expires_at — optional per-key expiry (SEC-07c)

Adds a single NULLABLE ``expires_at`` column to ``api_key``.

**The backfill is the trap — do NOT "tidy it up".** dsec-hub's and dsec-app's
shared *service* keys (the ones that mint tokens and fetch member cards) are old.
Setting ``expires_at = created_at + 180 days`` on existing rows would put a timer
on a production outage — there is no staging to notice. So every pre-existing row
stays NULL, and ``core.apikeys.verify_key`` treats NULL as "never expires":

    if row.expires_at is not None and row.expires_at <= now(): return None

Only NEWLY minted keys get the 180-day default (stamped in the app layer, not
here — see ``core.apikeys.default_key_expiry``). A freshly added nullable column
is NULL for all existing rows by definition, so there is no data-migration step;
the docstring is the safeguard against a future "add a default backfill" edit.

HAND-WRITTEN (never autogenerated against Neon — see the team rule). Idempotent
and additive. The SQLite dev/test schema is built from the models + stamped head
and never replays this chain, so the guard also keeps it a no-op there.

Revision ID: d8b3f6a1c4e7
Revises: c7d2e9f4a1b6
Create Date: 2026-08-30
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "d8b3f6a1c4e7"
down_revision: Union[str, Sequence[str], None] = "c7d2e9f4a1b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def upgrade() -> None:
    if "expires_at" not in _columns("api_key"):
        # Nullable → every existing row is NULL (never expires). No backfill.
        op.add_column(
            "api_key",
            sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        )


def downgrade() -> None:
    if "expires_at" in _columns("api_key"):
        op.drop_column("api_key", "expires_at")
