"""task.parent_task_id: one-level subtasks

Adds `task.parent_task_id` — a self-referential FK so a task can have child
"subtask" cards (one level only, enforced in the app). Children cascade-delete
with their parent at the DB level (and the app cascade-archives them, the common
path). Existing tasks keep parent_task_id NULL (top-level), so nothing changes
for current data.

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Idempotent: inspects the live schema first and only adds what's missing.

Revision ID: d9e2b6a4c1f8
Revises: b8d2f4a6c0e1
Create Date: 2026-06-17
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "d9e2b6a4c1f8"
down_revision: Union[str, Sequence[str], None] = "b8d2f4a6c0e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FK_NAME = "task_parent_task_id_fkey"
IX_NAME = "ix_task_parent_task_id"


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def _fks(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {fk["name"] for fk in insp.get_foreign_keys(table)}


def _indexes(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {ix["name"] for ix in insp.get_indexes(table)}


def upgrade() -> None:
    if "parent_task_id" not in _columns("task"):
        op.add_column("task", sa.Column("parent_task_id", sa.Integer(), nullable=True))
    if FK_NAME not in _fks("task"):
        op.create_foreign_key(FK_NAME, "task", "task", ["parent_task_id"], ["id"], ondelete="CASCADE")
    if IX_NAME not in _indexes("task"):
        op.create_index(IX_NAME, "task", ["parent_task_id"])


def downgrade() -> None:
    if IX_NAME in _indexes("task"):
        op.drop_index(IX_NAME, table_name="task")
    if FK_NAME in _fks("task"):
        op.drop_constraint(FK_NAME, "task", type_="foreignkey")
    if "parent_task_id" in _columns("task"):
        op.drop_column("task", "parent_task_id")
