"""usage_event: per-actor activity log (dashboard + MCP)

HAND-WRITTEN (not autogenerated) — see the dusa_weekly_imports note. CREATE-only.

Revision ID: e1c5a7d93f02
Revises: d4b8e1a6f29c
Create Date: 2026-06-14
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "e1c5a7d93f02"
down_revision: Union[str, Sequence[str], None] = "d4b8e1a6f29c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "usage_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("actor_label", sa.String(length=256), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("path", sa.String(length=512), nullable=True),
        sa.Column("detail", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usage_event", schema=None) as b:
        b.create_index(b.f("ix_usage_event_actor_type"), ["actor_type"], unique=False)
        b.create_index(b.f("ix_usage_event_actor_id"), ["actor_id"], unique=False)
        b.create_index(b.f("ix_usage_event_actor_label"), ["actor_label"], unique=False)
        b.create_index(b.f("ix_usage_event_source"), ["source"], unique=False)
        b.create_index(b.f("ix_usage_event_action"), ["action"], unique=False)
        b.create_index(b.f("ix_usage_event_target_type"), ["target_type"], unique=False)
        b.create_index(b.f("ix_usage_event_created_at"), ["created_at"], unique=False)


def downgrade() -> None:
    op.drop_table("usage_event")
