"""events.ticket_url — public buy-tickets / register link

Adds one nullable column to `events`:
  * ticket_url — free-form URL for buying tickets or registering, surfaced on
    the website event card + detail page (null = no external ticketing).

Idempotent + HAND-WRITTEN (not autogenerated) — only ADDs against live Neon.

Revision ID: e1f2a3b4c5d6
Revises: d5e6f7a8b9c0
Create Date: 2026-06-15
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "e1f2a3b4c5d6"
down_revision: Union[str, Sequence[str], None] = "d5e6f7a8b9c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def upgrade() -> None:
    if "ticket_url" not in _columns("events"):
        op.add_column("events", sa.Column("ticket_url", sa.String(length=1024), nullable=True))


def downgrade() -> None:
    if "ticket_url" in _columns("events"):
        op.drop_column("events", "ticket_url")
