"""partner.show_on_website: publish a partner's logo

Adds `partner.show_on_website` — the opt-in flag that publishes a partner's
logo on the public pages of the events it is linked to. Mirrors
`sponsors.show_on_website`:
  * False (default) — internal: the partner stays in the dashboard only
  * True            — published: its logo appears on the public event pages

Partners start internal; an exec flips this per partner when they want the
collaboration shown publicly. Existing partners keep the default (False), so
this never silently publishes anyone.

Idempotent: inspects the live schema first and only adds the column if missing
(the `partner` table was created by d7e3b1f9a2c5 without it).

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Revision ID: e2f4c6a8b1d3
Revises: d7e3b1f9a2c5
Create Date: 2026-06-16
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "e2f4c6a8b1d3"
down_revision: Union[str, Sequence[str], None] = "d7e3b1f9a2c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def upgrade() -> None:
    if "show_on_website" not in _columns("partner"):
        op.add_column(
            "partner",
            sa.Column("show_on_website", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        )


def downgrade() -> None:
    if "show_on_website" in _columns("partner"):
        op.drop_column("partner", "show_on_website")
