"""partner contact, socials & relationship status

Adds CRM-lite fields to `partner` so a collaborator club can be tracked before
and while we work with it:
  * email, instagram, linkedin, facebook — contact + social handles (all
    nullable, like the existing `website`).
  * status — the lightweight relationship pipeline (NOT the full sponsor CRM):
        lead -> contacted -> active -> inactive
    New rows default to "lead" (a freshly sourced club). EXISTING partners are
    backfilled to "active" so the rows that were already real collaborators
    don't suddenly read as cold leads.

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Idempotent: inspects the live schema first and only adds each column if missing,
and only backfills `status` in the run that actually adds the column (so a rerun
never clobbers statuses an exec has since changed).

Revision ID: e3a7c5f1b9d4
Revises: d3b7f1a9c5e2
Create Date: 2026-06-21
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "e3a7c5f1b9d4"
down_revision: Union[str, Sequence[str], None] = "d3b7f1a9c5e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def upgrade() -> None:
    cols = _columns("partner")

    for name in ("email", "instagram", "linkedin", "facebook"):
        if name not in cols:
            op.add_column("partner", sa.Column(name, sa.String(length=256), nullable=True))

    if "status" not in cols:
        op.add_column(
            "partner",
            sa.Column(
                "status",
                sa.String(length=32),
                server_default=sa.text("'lead'"),
                nullable=False,
            ),
        )
        op.create_index("ix_partner_status", "partner", ["status"])
        # Existing partners are real collaborators, not cold leads — mark them
        # active. Only runs the first time (we just added the column above).
        op.execute("UPDATE partner SET status = 'active'")


def downgrade() -> None:
    cols = _columns("partner")
    if "status" in cols:
        op.drop_index("ix_partner_status", table_name="partner")
        op.drop_column("partner", "status")
    for name in ("facebook", "linkedin", "instagram", "email"):
        if name in cols:
            op.drop_column("partner", name)
