"""oauth_client revocation: add revoked + first_seen_ip (NEW-APIROUTERS-04)

Open Dynamic Client Registration (RFC 7591) means a malicious MCP client can't be
stopped at registration — it has to be revocable afterwards. Adds two columns to
``oauth_client``:

  * revoked        — bool, NOT NULL, server_default false, indexed. ``get_client``
                     filters on it, so a revoked client is invisible to
                     /oauth/authorize and /oauth/token. Every existing row gets
                     false, so nothing breaks on deploy.
  * first_seen_ip  — nullable str(64): the IP that registered the client, for
                     triage. Backfilled to NULL for pre-existing rows.

HAND-WRITTEN (never autogenerated against Neon — the same DB is also described by
two independent Drizzle schemas, so autogenerate would emit spurious drops for
tables that aren't ours). Additive + idempotent. The SQLite dev/test schema is
built from the models + stamped head and never replays this chain.

Revision ID: e9c4a7b2d5f8
Revises: d8b3f6a1c4e7
Create Date: 2026-08-30
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "e9c4a7b2d5f8"
down_revision: Union[str, Sequence[str], None] = "d8b3f6a1c4e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_INDEX = "ix_oauth_client_revoked"


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def _indexes(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {i["name"] for i in insp.get_indexes(table)}


def upgrade() -> None:
    cols = _columns("oauth_client")
    if "revoked" not in cols:
        op.add_column(
            "oauth_client",
            sa.Column(
                "revoked", sa.Boolean(), nullable=False, server_default=sa.text("false")
            ),
        )
    if _INDEX not in _indexes("oauth_client"):
        op.create_index(_INDEX, "oauth_client", ["revoked"])
    if "first_seen_ip" not in cols:
        op.add_column(
            "oauth_client", sa.Column("first_seen_ip", sa.String(length=64), nullable=True)
        )


def downgrade() -> None:
    if _INDEX in _indexes("oauth_client"):
        op.drop_index(_INDEX, table_name="oauth_client")
    cols = _columns("oauth_client")
    if "first_seen_ip" in cols:
        op.drop_column("oauth_client", "first_seen_ip")
    if "revoked" in cols:
        op.drop_column("oauth_client", "revoked")
