"""event_connection links

Adds a single, lightweight join table for **symmetric, visual-only links
between two events** — "these events are related" (a series, a follow-up, a
kickoff→closing pair). The link carries no behaviour; it just lets the
dashboard and the public site show how events relate.

* `event_connection` — many-to-many event<->event. A pair is stored canonically
  (`event_a_id < event_b_id`, enforced in the app layer) so it has exactly one
  row regardless of which event it was added from; the UNIQUE constraint
  de-duplicates it. An optional `label` (e.g. "Series") is shown on both events.

HAND-WRITTEN (not autogenerated) — live Neon carries RBAC objects created outside
Alembic, so autogenerate would emit DROPs. This migration only CREATEs, and
skips the table if it already exists so a re-run is safe.

Revision ID: f1b3d5a7c9e2
Revises: e2f4c6a8b1d3
Create Date: 2026-06-16
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "f1b3d5a7c9e2"
down_revision: Union[str, Sequence[str], None] = "e2f4c6a8b1d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ts(name: str) -> sa.Column:
    return sa.Column(name, sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)


def _archived() -> sa.Column:
    return sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False)


def _tables() -> set[str]:
    return set(sa.inspect(op.get_bind()).get_table_names())


def upgrade() -> None:
    if "event_connection" not in _tables():
        op.create_table(
            "event_connection",
            sa.Column("id", sa.Integer(), nullable=False),
            # Canonical ordering: event_a_id is always the smaller of the two ids.
            sa.Column("event_a_id", sa.Integer(), nullable=False),
            sa.Column("event_b_id", sa.Integer(), nullable=False),
            # Optional label shown on both events, e.g. "Series" / "Follow-up".
            sa.Column("label", sa.String(length=64), nullable=True),
            _ts("created_at"),
            _ts("updated_at"),
            _archived(),
            sa.ForeignKeyConstraint(["event_a_id"], ["events.id"], name="event_connection_event_a_id_fkey"),
            sa.ForeignKeyConstraint(["event_b_id"], ["events.id"], name="event_connection_event_b_id_fkey"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("event_a_id", "event_b_id", name="uq_event_connection"),
        )
        with op.batch_alter_table("event_connection", schema=None) as b:
            b.create_index(b.f("ix_event_connection_event_a_id"), ["event_a_id"], unique=False)
            b.create_index(b.f("ix_event_connection_event_b_id"), ["event_b_id"], unique=False)
            b.create_index(b.f("ix_event_connection_archived"), ["archived"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("event_connection", schema=None) as b:
        b.drop_index(b.f("ix_event_connection_archived"))
        b.drop_index(b.f("ix_event_connection_event_b_id"))
        b.drop_index(b.f("ix_event_connection_event_a_id"))
    op.drop_table("event_connection")
