"""api_key.parent_key_id — self-mint lineage for cascade revocation (SEC-06 d3)

Adds a nullable self-referential ``parent_key_id`` FK to ``api_key``. A key minted
through ``POST /admin/keys/self`` records the CALLER key as its parent; revoking a
parent then cascades to its children (``admin.revoke_key``), so a child key can no
longer outlive the revocation of the key that created it.

Nullable → every PRE-EXISTING row is NULL (an owner/service key with no parent),
so there is no backfill and nothing breaks on deploy. Additive + idempotent.

HAND-WRITTEN (never autogenerated against Neon — the same DB carries independent
Drizzle schemas autogenerate would try to "fix"). The SQLite dev/test schema is
built from the models + stamped head and never replays this chain.

Revision ID: f1d5b8c3a6e9
Revises: e9c4a7b2d5f8
Create Date: 2026-08-30
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "f1d5b8c3a6e9"
down_revision: Union[str, Sequence[str], None] = "e9c4a7b2d5f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_INDEX = "ix_api_key_parent_key_id"
_FK = "fk_api_key_parent_key_id"


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def _indexes(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {i["name"] for i in insp.get_indexes(table)}


def _fk_names(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {fk.get("name") for fk in insp.get_foreign_keys(table)}


def upgrade() -> None:
    if "parent_key_id" not in _columns("api_key"):
        op.add_column("api_key", sa.Column("parent_key_id", sa.Integer(), nullable=True))
    if _INDEX not in _indexes("api_key"):
        op.create_index(_INDEX, "api_key", ["parent_key_id"])
    # Self-referential FK, created only when the exact named constraint is absent.
    # Inspecting for the name (rather than catching every exception) keeps this
    # genuinely idempotent AND lets a real DDL error surface on a live-Neon run
    # instead of being swallowed — a blanket except would hide it and, since a
    # failed DDL aborts the transaction anyway, wouldn't actually make it re-runnable.
    if _FK not in _fk_names("api_key"):
        op.create_foreign_key(_FK, "api_key", "api_key", ["parent_key_id"], ["id"])


def downgrade() -> None:
    if _FK in _fk_names("api_key"):
        op.drop_constraint(_FK, "api_key", type_="foreignkey")
    if _INDEX in _indexes("api_key"):
        op.drop_index(_INDEX, table_name="api_key")
    if "parent_key_id" in _columns("api_key"):
        op.drop_column("api_key", "parent_key_id")
