"""media_asset: uploaded images for events & projects (Supabase Storage)

Adds the `media_asset` table. Binaries live in Supabase Storage; only the public
URLs + metadata land here. Polymorphic by (entity_type, entity_id) — no FK, so
one table serves both events and projects.

HAND-WRITTEN (not autogenerated) — see the workspace_tables migration note:
live Neon carries RBAC objects created outside Alembic, so autogenerate would
emit DROPs. This migration only CREATEs.

Revision ID: f3a9d2b7c4e1
Revises: e1c5a7d93f02
Create Date: 2026-06-15
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "f3a9d2b7c4e1"
down_revision: Union[str, Sequence[str], None] = "e1c5a7d93f02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ts(name: str) -> sa.Column:
    return sa.Column(name, sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)


def _archived() -> sa.Column:
    return sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False)


def upgrade() -> None:
    op.create_table(
        "media_asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=16), nullable=False),  # event|project
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),  # image|poster|banner
        sa.Column("alt_text", sa.String(length=512), nullable=True),
        sa.Column("original_filename", sa.String(length=512), nullable=True),
        sa.Column("webp_url", sa.String(length=1024), nullable=False),
        sa.Column("png_url", sa.String(length=1024), nullable=False),
        sa.Column("webp_path", sa.String(length=512), nullable=False),
        sa.Column("png_path", sa.String(length=512), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        _ts("created_at"),
        _ts("updated_at"),
        _archived(),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("media_asset", schema=None) as b:
        b.create_index("ix_media_asset_entity", ["entity_type", "entity_id"], unique=False)
        b.create_index(b.f("ix_media_asset_archived"), ["archived"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("media_asset", schema=None) as b:
        b.drop_index(b.f("ix_media_asset_archived"))
        b.drop_index("ix_media_asset_entity")
    op.drop_table("media_asset")
