"""events review form — Tally post-event review link

Adds three nullable columns to `events` for the post-event review feature:
  * review_form_id          — Tally form id (used to fetch submissions)
  * review_form_url         — public fill link (https://tally.so/r/<id>)
  * review_form_created_at  — when the form was created

Idempotent + HAND-WRITTEN (not autogenerated) — only ADDs against live Neon.

Revision ID: f4b9c1d3e5a7
Revises: c3f7b1a9d2e4
Create Date: 2026-06-15
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "f4b9c1d3e5a7"
down_revision: Union[str, Sequence[str], None] = "c3f7b1a9d2e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def upgrade() -> None:
    cols = _columns("events")
    if "review_form_id" not in cols:
        op.add_column("events", sa.Column("review_form_id", sa.String(length=64), nullable=True))
    if "review_form_url" not in cols:
        op.add_column("events", sa.Column("review_form_url", sa.String(length=512), nullable=True))
    if "review_form_created_at" not in cols:
        op.add_column(
            "events",
            sa.Column("review_form_created_at", sa.DateTime(timezone=True), nullable=True),
        )


def downgrade() -> None:
    cols = _columns("events")
    if "review_form_created_at" in cols:
        op.drop_column("events", "review_form_created_at")
    if "review_form_url" in cols:
        op.drop_column("events", "review_form_url")
    if "review_form_id" in cols:
        op.drop_column("events", "review_form_id")
