"""document custom pages: slug + publish + nav + block content

Lets a committee Document be published as a public website page at
https://dsec.club/<slug>. Adds to the `document` table:
  * slug            — stable, unique URL key (NULL until published as a page)
  * is_public       — draft/published gate for the /website/pages feed
  * nav_label       — optional label when shown in the site nav (else title)
  * show_in_nav     — surface this page in the public site navigation
  * nav_area        — "header" | "footer" (where show_in_nav places it)
  * nav_order       — sort order within the nav / pages list
  * seo_description — meta/OG description for the page <head>
  * cover_image_url — OG/share image URL

Ordinary committee docs are unaffected: slug stays NULL, is_public false, so
NOTHING that exists today leaks onto the public site. A doc only becomes a live
page once the dashboard gives it a slug and flips is_public — hence NO backfill
(unlike events, internal notes must NOT become public on launch).

The block payload lives in the existing `content_json` JSON column (added with
the model originally, no new column needed).

Idempotent: inspects the live schema first and only adds what's missing.

HAND-WRITTEN (not autogenerated) — only ADDs against live Neon, never a drop on
upgrade. (See the team rule against `alembic --autogenerate` on Neon.)

Revision ID: f4c8e2a1d9b7
Revises: a4e8c2f6d9b1
Create Date: 2026-06-28
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "f4c8e2a1d9b7"
down_revision: Union[str, Sequence[str], None] = "a4e8c2f6d9b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {c["name"] for c in insp.get_columns(table)}


def _indexes(table: str) -> set[str]:
    insp = sa.inspect(op.get_bind())
    return {ix["name"] for ix in insp.get_indexes(table)}


def upgrade() -> None:
    cols = _columns("document")

    if "slug" not in cols:
        op.add_column("document", sa.Column("slug", sa.String(length=256), nullable=True))
    if "is_public" not in cols:
        op.add_column(
            "document",
            sa.Column(
                "is_public", sa.Boolean(), nullable=False, server_default=sa.text("false")
            ),
        )
    if "nav_label" not in cols:
        op.add_column("document", sa.Column("nav_label", sa.String(length=128), nullable=True))
    if "show_in_nav" not in cols:
        op.add_column(
            "document",
            sa.Column(
                "show_in_nav", sa.Boolean(), nullable=False, server_default=sa.text("false")
            ),
        )
    if "nav_area" not in cols:
        op.add_column("document", sa.Column("nav_area", sa.String(length=16), nullable=True))
    if "nav_order" not in cols:
        op.add_column(
            "document",
            sa.Column("nav_order", sa.Integer(), nullable=False, server_default=sa.text("0")),
        )
    if "seo_description" not in cols:
        op.add_column(
            "document", sa.Column("seo_description", sa.String(length=512), nullable=True)
        )
    if "cover_image_url" not in cols:
        op.add_column(
            "document", sa.Column("cover_image_url", sa.String(length=512), nullable=True)
        )

    idx = _indexes("document")
    # Unique index on slug: existing rows are all NULL, and NULLs are distinct in
    # both Postgres and SQLite, so the uniqueness applies only to real slugs.
    if "ix_document_slug" not in idx:
        op.create_index("ix_document_slug", "document", ["slug"], unique=True)
    if "ix_document_is_public" not in idx:
        op.create_index("ix_document_is_public", "document", ["is_public"])


def downgrade() -> None:
    idx = _indexes("document")
    if "ix_document_is_public" in idx:
        op.drop_index("ix_document_is_public", table_name="document")
    if "ix_document_slug" in idx:
        op.drop_index("ix_document_slug", table_name="document")
    cols = _columns("document")
    for col in (
        "cover_image_url",
        "seo_description",
        "nav_order",
        "nav_area",
        "show_in_nav",
        "nav_label",
        "is_public",
        "slug",
    ):
        if col in cols:
            op.drop_column("document", col)
