"""game tables: game, game_round, game_player, game_account_link, game_attempt, draw_cycle

The games platform — arcade (Flappy Duck) + Codle. Six tables that hold the game
registry, the daily/period rounds, the per-account player identity, the Discord
link, the one shared points ledger, and the monthly draw. The API is the only
brain; these tables back it.

HAND-WRITTEN (not autogenerated) — live Neon carries RBAC / app-owned objects
created outside Alembic, so autogenerate would emit DROPs. This migration only
CREATEs against live Neon, never a drop on upgrade. (See the team rule against
`alembic --autogenerate` on Neon.) Idempotent: it inspects the live schema first
and only creates a table that is missing, so a re-run is safe.

Revision ID: f7c2a9d4b1e6
Revises: e3a7c5f1b9d4
Create Date: 2026-06-24
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "f7c2a9d4b1e6"
down_revision: Union[str, Sequence[str], None] = "e3a7c5f1b9d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ts(name: str) -> sa.Column:
    return sa.Column(name, sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)


def _archived() -> sa.Column:
    return sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False)


def _tables() -> set[str]:
    return set(sa.inspect(op.get_bind()).get_table_names())


def upgrade() -> None:
    existing = _tables()

    # --- game (registry) -----------------------------------------------------
    if "game" not in existing:
        op.create_table(
            "game",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("slug", sa.String(length=64), nullable=False),
            sa.Column("name", sa.String(length=128), nullable=False),
            sa.Column("surface", sa.String(length=16), server_default=sa.text("'both'"), nullable=False),
            sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
            _ts("created_at"),
            _ts("updated_at"),
            _archived(),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("game", schema=None) as b:
            b.create_index(b.f("ix_game_slug"), ["slug"], unique=True)
            b.create_index(b.f("ix_game_active"), ["active"], unique=False)
            b.create_index(b.f("ix_game_archived"), ["archived"], unique=False)

    # --- game_round (the shared daily/period puzzle) -------------------------
    if "game_round" not in existing:
        op.create_table(
            "game_round",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("game_id", sa.Integer(), nullable=False),
            sa.Column("period_key", sa.String(length=32), nullable=False),
            # FULL puzzle incl. any answer — server-only, never returned raw.
            sa.Column("payload", sa.JSON(), nullable=True),
            sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
            _ts("created_at"),
            _ts("updated_at"),
            _archived(),
            sa.ForeignKeyConstraint(["game_id"], ["game.id"], name="game_round_game_id_fkey"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("game_id", "period_key", name="uq_game_round"),
        )
        with op.batch_alter_table("game_round", schema=None) as b:
            b.create_index(b.f("ix_game_round_game_id"), ["game_id"], unique=False)
            b.create_index(b.f("ix_game_round_period_key"), ["period_key"], unique=False)
            b.create_index(b.f("ix_game_round_archived"), ["archived"], unique=False)

    # --- game_player (one per portal/student account) ------------------------
    if "game_player" not in existing:
        op.create_table(
            "game_player",
            sa.Column("id", sa.Integer(), nullable=False),
            # dsec-app portal_account.id — plain int, app-owned table, no FK.
            sa.Column("account_id", sa.Integer(), nullable=False),
            sa.Column("email", sa.String(length=256), nullable=True),
            sa.Column("display_name", sa.String(length=128), nullable=True),
            _ts("created_at"),
            _ts("updated_at"),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("game_player", schema=None) as b:
            b.create_index(b.f("ix_game_player_account_id"), ["account_id"], unique=True)
            b.create_index(b.f("ix_game_player_email"), ["email"], unique=False)

    # --- game_account_link (Discord <-> player) ------------------------------
    if "game_account_link" not in existing:
        op.create_table(
            "game_account_link",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("player_id", sa.Integer(), nullable=False),
            sa.Column("discord_user_id", sa.String(length=32), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.ForeignKeyConstraint(
                ["player_id"], ["game_player.id"], name="game_account_link_player_id_fkey", ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("game_account_link", schema=None) as b:
            b.create_index(b.f("ix_game_account_link_player_id"), ["player_id"], unique=False)
            b.create_index(b.f("ix_game_account_link_discord_user_id"), ["discord_user_id"], unique=True)

    # --- game_attempt (the single points ledger for ALL surfaces) ------------
    if "game_attempt" not in existing:
        op.create_table(
            "game_attempt",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("game_id", sa.Integer(), nullable=False),
            sa.Column("round_id", sa.Integer(), nullable=True),
            sa.Column("player_id", sa.Integer(), nullable=False),
            sa.Column("raw_score", sa.Float(), server_default=sa.text("0"), nullable=False),
            sa.Column("points", sa.Integer(), server_default=sa.text("0"), nullable=False),
            sa.Column("detail", sa.JSON(), nullable=True),
            sa.Column("is_member_play", sa.Boolean(), server_default=sa.text("false"), nullable=False),
            sa.Column("surface", sa.String(length=16), nullable=True),
            sa.Column("played_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.ForeignKeyConstraint(["game_id"], ["game.id"], name="game_attempt_game_id_fkey"),
            sa.ForeignKeyConstraint(["round_id"], ["game_round.id"], name="game_attempt_round_id_fkey"),
            sa.ForeignKeyConstraint(["player_id"], ["game_player.id"], name="game_attempt_player_id_fkey"),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("game_attempt", schema=None) as b:
            b.create_index(b.f("ix_game_attempt_game_id"), ["game_id"], unique=False)
            b.create_index(b.f("ix_game_attempt_round_id"), ["round_id"], unique=False)
            b.create_index(b.f("ix_game_attempt_player_id"), ["player_id"], unique=False)
            b.create_index("ix_game_attempt_game_round_player", ["game_id", "round_id", "player_id"], unique=False)
            b.create_index("ix_game_attempt_player_played", ["player_id", "played_at"], unique=False)

    # --- draw_cycle (monthly rollup; highest member points wins) -------------
    if "draw_cycle" not in existing:
        op.create_table(
            "draw_cycle",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("period_key", sa.String(length=16), nullable=False),
            sa.Column("status", sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
            sa.Column("winner_player_id", sa.Integer(), nullable=True),
            sa.Column("total_points_snapshot", sa.JSON(), nullable=True),
            sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
            _ts("created_at"),
            _ts("updated_at"),
            _archived(),
            sa.ForeignKeyConstraint(
                ["winner_player_id"], ["game_player.id"], name="draw_cycle_winner_player_id_fkey"
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("draw_cycle", schema=None) as b:
            b.create_index(b.f("ix_draw_cycle_period_key"), ["period_key"], unique=True)
            b.create_index(b.f("ix_draw_cycle_status"), ["status"], unique=False)
            b.create_index(b.f("ix_draw_cycle_winner_player_id"), ["winner_player_id"], unique=False)
            b.create_index(b.f("ix_draw_cycle_archived"), ["archived"], unique=False)


def downgrade() -> None:
    existing = _tables()
    # Children before parents to respect FK order.
    for table in ("game_attempt", "game_account_link", "draw_cycle", "game_round", "game_player", "game"):
        if table in existing:
            op.drop_table(table)
